### ISSUE TITLE
how to use middleware Auth for Log View route?

### ISSUE THREAD

**Issue by terrywamg** [ARCANEDEV/LogViewer#117]
I used middleware "Auth" to controll the visit right of log-view route, but always fail after adding config item as following: 

```php
'route'         => [
    'enabled'    => true,

    'attributes' => [
        'prefix'     => 'log-viewer',

        'middleware' => 'auth',
    ],
],
```

if the `middleware=>null`, I can visit the route: /log-viewer, if the `middleware=>'auth'`, even the user has login, but I can not visit to the route "/log-viewer".

Maybe the middleware "auth" has be loaded later than Log-Viewer's route register, but I am not sure. I need some one's help.

Who knows the reason? thanks in advance.

**Comment by arcanedev-maroc** [comment]
If you're using Laravel 5.2 or +, here is your answer: https://github.com/ARCANEDEV/LogViewer/issues/69#issuecomment-239631336
