### ISSUE TITLE
Undefined variable: reports on 4.2.0

### ISSUE THREAD

**Issue by praditha** [ARCANEDEV/LogViewer#120]
Hi,

I got this error when I update the log-viewer from 4.1.0 to 4.2.0

`Undefined variable: reports (View: /var/www/html/mpos-siloam-api/resources/views/vendor/log-viewer/dashboard.blade.php)`

Then I downgrade the version to 4.1.0 and it's working again.
I have no idea how to fix this, I already debug the code, but still not find the clue.

Thanks.

**Comment by icodebuster** [comment]
Hi @praditha 

Please run this artisan command

    php artisan log-viewer:publish --force

The above command should fix the issue.

**NOTE:** You need to again add any changes done to the `config\log-viewer` file.

**Comment by praditha** [comment]
Ok thanks @icodebuster your solutions fixed the error.
But as you said, I need to re-add my previous configuration on `config\log-viewer`, and also my changes on `resources/views/vendor/log-viewer`.

Do you know what is the changes on version 4.2.0..?

**Comment by arcanedev-maroc** [comment]
Changes: https://github.com/ARCANEDEV/LogViewer/compare/4.1.0...master

You can also lock the `log-viewer` version if you're using it in your backend.
