### ISSUE TITLE
Add timezone for parsing the log date

### ISSUE THREAD

**Issue by mb-programmer** [ARCANEDEV/LogViewer#121]
Hello 
thanks for your great job
i think it is good to have the option to set different timezone for viewing the logs
for example i have an application for different timezone and i want to see the logs in my timezone

**Comment by arcanedev-maroc** [comment]
Hi @mb-programmer,

You can use the Log Entry's `datetime` property to format the date with a custom timezone in your views: https://github.com/ARCANEDEV/LogViewer/blob/master/src/Entities/LogEntry.php#L26-L27

**Comment by mb-programmer** [comment]
thanks @arcanedev-maroc 
it's good to have this option in config file.

**Comment by arcanedev-maroc** [comment]
You already have this in your laravel app config.

Check this: https://github.com/laravel/laravel/blob/master/config/app.php#L56-L67

**Comment by mb-programmer** [comment]
I know that. i mean in the log config file.
for example consider i have an application for a foreign country and i want to see the logs in my timezone.

**Comment by arcanedev-maroc** [comment]
I'm going to leave this suggestion open and see if other users are interested.

**Comment by eppak** [comment]
+1

**Comment by AdrianKuriata** [comment]
Yea sure, i think this is good idea to add format for date into config logviewier file, i mean something like `'date-format' => 'd.m.Y, H:i:s'` - and i don't think so this can be hardly to change in into views files, mean `date(config('log-viewier.date-format, strtotime($log->created_at)));`

**Comment by eppak** [comment]
@AdrianKuriata We need to consider timezone too

**Comment by arcanedev-maroc** [comment]
Hi everybody, feel free to make a PR 👍

**Comment by eppak** [comment]
@AdrianKuriata Yes is an option, but this involve all the app to be localized, sometime i prefer to have a UTC global configuration and extract the TZ from user preferences

**Comment by AdrianKuriata** [comment]
@eppak This is more powerfull for developer whos using log viewier like an additional, if you want exacly use for you UTC timezone and other like Europe/Madrit timezone for other user it should be implemented into application, not in package - and now you can do support parse date for log viewier from app.php config or set into config log viewier support for this, in my opinion it shouldnt be did into log viewier.

**Comment by eppak** [comment]
@AdrianKuriata I'm agree that make heavy modification directly to the package is not a good option, but i think we can do it as flexible as possible. Imagine an app that is configured as UTC globally, users have their own time zone (in a large and distribuited application can happen). What you suggest? Maybe the format can be a function? The package have it's local configuration right? We can work there.

**Comment by AdrianKuriata** [comment]
@eppak I think we can detect user timezone by his IP, i mean use GEO API for detect timezone and convert it to display for user used some function for this.
