### ISSUE TITLE
Problem when setting Middleware

### ISSUE THREAD

**Issue by Arwany** [ARCANEDEV/LogViewer#122]
Hi,

I set the middleware to the following in the `config/log-viewer.php` file:

`'middleware' => 'special',`

Where in special, it just checks if the user has a special field set to value 1, like this:

`if ($this->auth->user()->special == 1)){
return $next($request);
}`

But I have noticed that the $this->auth->user() is null, and $this->auth->check() returns false.

What did I miss?

Thank you, great project btw.

**Comment by arcanedev-maroc** [comment]
Hi,

You forgot to add the basic `web` middleware, try this:

```php
'middleware' => ['web', 'special'],
```
