### ISSUE TITLE
Forgot to update the version in the footer

### ISSUE THREAD

**Issue by GertjanRoke** [ARCANEDEV/LogViewer#123]
Hello,

You forgot to update the version in the footer to `4.2.0`.
Not that this is breaking or something but I just wanted to make you aware of this.

**Comment by arcanedev-maroc** [comment]
Hi @GertjanRoke,

Thanks for that, i just forgot to bump the LogViewer's version.

Done: https://github.com/ARCANEDEV/LogViewer/blob/master/src/LogViewer.php#L23
