### ISSUE TITLE
How to add custom route for logviewer panel

### ISSUE THREAD

**Issue by umairali** [ARCANEDEV/LogViewer#130]
- LogViewer Version: 4.3
- Laravel Version: 5.4

### Description:
I am trying with http://example.com/log-viewer this url but I already used this url in my project so how i create new url (route) for logviewer panel.

**Comment by arcanedev-maroc** [comment]
You can edit the `log-viewer` package url by changing the `prefix` value in the `log-viewer.php` config file: https://github.com/ARCANEDEV/LogViewer/blob/master/config/log-viewer.php#L39

**Comment by umairali** [comment]
ok thanks
