### ISSUE TITLE
How to add login authentication in log viewer panel

### ISSUE THREAD

**Issue by umairali** [ARCANEDEV/LogViewer#131]
- LogViewer Version: 4.3
- Laravel Version: 5.4

### Description:
How to add login authentication in log viewer panel.

**Comment by arcanedev-maroc** [comment]
Check this: https://github.com/ARCANEDEV/LogViewer/issues/69

And if you have any other question about this package, make sure to search in the previous closed issues or by the labels like this: [question](https://github.com/ARCANEDEV/LogViewer/issues?q=label%3Aquestion+is%3Aclosed)
