### ISSUE TITLE
Pretty Print Context

### ISSUE THREAD

**Issue by Towerful** [ARCANEDEV/LogViewer#134]
This package is great! It's made my life so much easier!

However, the context is a bit unreadable.  
Would it be possible to have the context pretty-printed/syntax-highlighted, then toggle-able like the stack trace is?

**Comment by arcanedev-maroc** [comment]
Feel free to make a PR 👍

**Comment by tonoslav** [comment]
Will this be implemented in future or not ? would be really useful, I use it in every log
