### ISSUE TITLE
Pattern for matching any log in log folder starting with laravel-

### ISSUE THREAD

**Issue by jonathan-bird** [ARCANEDEV/LogViewer#135]
I'm probably doing this wrong, so thought I'd ask first, but I can't get the pattern to work for all log files:

```php
'pattern'       => [
    'prefix'    => Filesystem::PATTERN_PREFIX,    // 'laravel-'
    'date'      => '.*',
    'extension' => Filesystem::PATTERN_EXTENSION, // '.log'
],
```

All of my log files are `laravel-cli-2016-04-10.log` and `laravel-fpm-fcgi-2017-04-10.log`

Any ideas? Is the regex wrong?

**Comment by arcanedev-maroc** [comment]
If you combine all the segements of your pattern you get this: `laravel-.*.log`.

Check these lines:

  * https://github.com/ARCANEDEV/LogViewer/blob/master/src/Utilities/Filesystem.php#L104-L107
  * https://github.com/ARCANEDEV/LogViewer/blob/master/src/Utilities/Filesystem.php#L186-L194
  * https://github.com/ARCANEDEV/LogViewer/blob/master/src/Utilities/Filesystem.php#L283-L290

**Comment by jonathan-bird** [comment]
Ah so it takes it as literal.

Is there a regex for any pattern?

**Comment by arcanedev-maroc** [comment]
For your case:

```php
'pattern'       => [
    'prefix'    => Filesystem::PATTERN_PREFIX.'(cli|fpm-fcgi)-',
    'date'      => Filesystem::PATTERN_DATE,
    'extension' => Filesystem::PATTERN_EXTENSION,
],
```

Link: http://regexr.com/3fnef

**Comment by jonathan-bird** [comment]
I tried `Filesystem::PATTERN_PREFIX.'-(cli|fpm-fcgi)'` but doesn't return anything.

**Comment by delmicio** [comment]
@jonathan-bird #164 is still open. Have you solved this?

**Comment by arcanedev-maroc** [comment]
I think the correct pattern is `Filesystem::PATTERN_PREFIX.'{cli,fpm-fcgi}-'` because it's for the `glob()` function, my bad.

But the LogViewer doesn't allow the display of multiple env logs with the same date:

```
laravel-cli-2018-01-03.log
laravel-fpm-fcgi-2018-01-03.log
```

See this method for more details: https://github.com/ARCANEDEV/LogViewer/blob/master/src/Utilities/Filesystem.php#L308-L312

**Comment by 327** [comment]
hi, does this problem has a solution?

**Comment by clydeortega14** [comment]
can we replace the original pattern?

**Comment by expired-brain** [comment]
> Arcanedev\LogViewer\Exceptions\FilesystemException
> The log(s) could not be located at : /www/storage/logs/laravel-{cli,fpm-fcgi}-2020-09-20.log
> 

Nothings works 👎

**Comment by expired-brain** [comment]
> I think the correct pattern is `Filesystem::PATTERN_PREFIX.'{cli,fpm-fcgi}-'` because it's for the `glob()` function, my bad.
> 
> But the LogViewer doesn't allow the display of multiple env logs with the same date:
> 
> ```
> laravel-cli-2018-01-03.log
> laravel-fpm-fcgi-2018-01-03.log
> ```
> 
> See this method for more details: https://github.com/ARCANEDEV/LogViewer/blob/master/src/Utilities/Filesystem.php#L308-L312

> Arcanedev\LogViewer\Exceptions\FilesystemException
> The log(s) could not be located at : /www/storage/logs/laravel-{cli,fpm-fcgi}-2020-09-20.log
> 

Nothings works 👎
