### ISSUE TITLE
Empty list after installation

### ISSUE THREAD

**Issue by avifatal** [ARCANEDEV/LogViewer#137]
- LogViewer Version: latest
- Laravel Version: latest
- PHP Version: 7.1

### Description:
After the installation I see an empty list (empty dashboard and empty logs).
the log file existed in storage/logs/laravel.log

`'log' => env('APP_LOG', 'daily'),`

thanks

**Comment by arcanedev-maroc** [comment]
It's not going to work with the old log file `storage/logs/laravel.log` (`single` mode).

The daily log files looks like this `storage/logs/laravel-YYYY-MM-DD.log`.

**Comment by avifatal** [comment]
How do i configure it?

**Comment by arcanedev-maroc** [comment]
You have two options:

  * Add `APP_LOG=daily` to you env file.
  * *OR* instead of `'log' => env('APP_LOG', 'daily'),` you can set it like this `'log' => 'daily'`

**Comment by avifatal** [comment]
Working, thanks
