### ISSUE TITLE
How to set password to my log viewer?

### ISSUE THREAD

**Issue by amirpiri** [ARCANEDEV/LogViewer#142]
I want to set password to avoid untrusted user see my logs. How can I do it?

**Comment by arcanedev-maroc** [comment]
Check this: https://github.com/ARCANEDEV/LogViewer/issues/69

And if you have any other question about this package, make sure to search in the previous closed issues or by the labels like this: [question](https://github.com/ARCANEDEV/LogViewer/issues?q=label%3Aquestion+is%3Aclosed)
