### ISSUE TITLE
package dependency

### ISSUE THREAD

**Issue by ruchisheth** [ARCANEDEV/LogViewer#149]
- LogViewer Version: 4.3
- Laravel Version: 5.2
- PHP Version: 5.6

### Description:
get this when trying to install package
**Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.**

**Comment by ruchisheth** [comment]
Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.

**Comment by arcanedev-maroc** [comment]
Your issue is not related to this package because it doesn't use the `egeloen/http-adapter` package.

You can check our dependencies: https://github.com/ARCANEDEV/LogViewer/blob/master/composer.json#L16-L24
