### ISSUE TITLE
Download Filename hardcoded

### ISSUE THREAD

**Issue by disto** [ARCANEDEV/LogViewer#150]
- LogViewer Version: 4.3.8
![screen shot 2017-06-28 at 15 26 02](https://user-images.githubusercontent.com/1729769/27639616-0a4527fa-5c17-11e7-86a4-72c05cea832c.png)

- Laravel Version: 5.4.24
- PHP Version: 7.0.10

### Description:
In the config file it is possible to enter a format file name of downloads
made from log-files.
However in the LogViewer.php file the file name is hardcoded.

### Steps To Reproduce:
Adjust format in config and download a logfile

**Comment by arcanedev-maroc** [comment]
Youn can specify a custom name for the log files to download in the second argument.

**Example 1:**

```php
log_viewer()->download('2017-06-27'); 
// This is basically is going to use the default format for the daily log: laravel-2017-06-27.log
```

**Example 2:**
```php
log_viewer()->download('2017-06-27', 'my-log-file.log'); 
// This is a custom name of the log file to download: my-log-file.log
```

So there is no need to add this in the config file because the hardcoded name is used as a fallback.

Thanks for the suggestion 👍
