### ISSUE TITLE
View only unique exceptions (i.e. Group repeated exceptions together)

### ISSUE THREAD

**Issue by charlizesmith** [ARCANEDEV/LogViewer#151]
- LogViewer Version: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#

### Description:
Hi,

Is it possible to view only unique exceptions (maybe with the number of times it occurred). Thus, it would have to group all the same exceptions together.

This would be tremendously helpful. I want to avoid using third-party applications like Sentry or BugSnag. 

Is it possible to make minor modification somehow to achieve this results?

Regards!

**Comment by charlizesmith** [comment]
Or at least is there an option to sort by "Header", so that I can sort and see all duplicate exceptions together. Then using pagination, I can see the different unique exceptions manually

**Comment by arcanedev-maroc** [comment]
You can implement your own logic for this.

The LogViewer is flexible and gives you a nice API to manage/view your logs.

By default, all logs are sorted/viewed by its timestamp. You can group/filter/sort the log entries the same way as you do with `Illuminate\Support\Collection` class, [check the documentation for more details](https://laravel.com/docs/5.4/collections).

Try to customize/create the routes/controllers/views and use LogViewer as an API.
