### ISSUE TITLE
Question routes doesn't work with other laravel app

### ISSUE THREAD

**Issue by InfinityWebMe** [ARCANEDEV/LogViewer#159]
- LogViewer Version: 4.3.8
- Laravel Version: 5.2
- PHP Version: 7.0.0

### Description:
I try to use this package with typicms ( https://github.com/TypiCMS/Base ). But i have a issue, i don't access to route of LogViewer ( https://github.com/TypiCMS/Base/issues/100 ).

I put the provider just after Vendor Service Providers but the route doesn't work. Except if in pp/http/routes.php i put this line Route::get('log-viewer'); ( for each LogViewer route ) ?!

Do you have any idea why it doesn't work ? 

Thanks a lot :)

**Comment by arcanedev-maroc** [comment]
**Replied:** https://github.com/TypiCMS/Base/issues/100#issuecomment-321265991
