### ISSUE TITLE
Q: is this only for Laravel logs or for any logfiles?

### ISSUE THREAD

**Issue by COLABORATI** [ARCANEDEV/LogViewer#160]
Just a question: is this only for logfiles created by Laravel or can it be used with any logfile format, e.g. apache, nginx, mysql etc.? Wouldn't it be good to mention this information in the Readme?

Thank you very much for your attention!

**Comment by arcanedev-maroc** [comment]
Good question.

This package works only for laravel apps, especially with [monolog](https://github.com/Seldaek/monolog) as a default log system (This is PHP).

**But**, we can add supports for other log files like `apache`, `nginx`, `mysql`.

Adding something like `Handlers` or `Readers` for each log file: LaravelLogReader, ApacheLogReader, NginxLogReader...

The problems: 

  * Are the different logs sharing the same records details (AKA entries) like header, timestamps, level, stack ...
  * Log strategy: daily log to keep files small.

Feel free to make a suggestion or PR to add support for other log's types 👍

**Comment by abishekrsrikaanth** [comment]
+1 on this as well. It will be great if we could define a list of directories to scan for reading log files. For example, I use `supervisor` to manage the queue workers and log output of the queues in a different directory.

**Comment by vesper8** [comment]
it would be great if your log viewer could auto-detect the presence of *.log files inside the /storage/logs folder and display all of those automatically

**Comment by keesh7663** [comment]
I agree that redirecting all system logs (nginx, mariadb, redis, php) to a centralized folder (/storage/logs) and being able to view them all in one place would make this the most valuable tool that any Laravel user could ever have.
