### ISSUE TITLE
Request for features on the Log Viewer

### ISSUE THREAD

**Issue by abishekrsrikaanth** [ARCANEDEV/LogViewer#161]
So far, loving the log viewer but have a request for a few features.

1. Ability to use our own layouts so it can be part of the existing UI.
2. An artisan command that can be used to delete logs. Would be good to have arguments that can allow deletion of logs beyond a certain date or number of days.

**Comment by arcanedev-maroc** [comment]
For the first point, you can check this answered issue: https://github.com/ARCANEDEV/LogViewer/issues/83

And the second point, laravel offers a feature to clean the logs files (`daily` logs) automatically by adding `log_max_files` to your `app.php` config file, check this section for more details: https://laravel.com/docs/5.4/errors#log-storage

I'm going to add the `delete all logs` feature when i got some spare time.

Cheers 👍
