### ISSUE TITLE
Empty page

### ISSUE THREAD

**Issue by klachhab** [ARCANEDEV/LogViewer#162]
- LogViewer Version: 4.3
- Laravel Version: 5.6.4
- PHP Version: 7.1.5

### Description:

Hi,

I installed and configured Laravel and LogViewer but logs list is empty and the LogViewer's dashboard is empty but the log files are full of errors

Can you help please ?

Links to screenshots :
https://ibb.co/nbko4v
https://ibb.co/n544cF
https://ibb.co/gNhCWa

**Comment by arcanedev-maroc** [comment]
Hi @klachhab,

Can you correct the laravel version ? `5.6.4` is not a correct version ?

Make sure you've installed/configured the package by following [the documentation](https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md).

Also, try to delete all the old logs and start testing it with new ones. You can do something in the routes like this:

```php
Route::get('test-log', function () {
    Log::info('This is a log info');
});

// Make sure it will generate a daily log file like: storage/logs/laravel-yyyy-mm-dd.log
```

And check if you can see it in the dashboard.

**Comment by klachhab** [comment]
I just resolved the problem
I changed the Logviewer version in composer.json file, i put "4.*" and updated dependencies
It worked very well
Thank you for the fast responses
![capture4](https://user-images.githubusercontent.com/30941070/29242306-6c67a03c-7f82-11e7-9830-00799627394f.PNG)

**Comment by arcanedev-maroc** [comment]
You're welcome 👍
