### ISSUE TITLE
S3 as 'storage-path'

### ISSUE THREAD

**Issue by s1rc** [ARCANEDEV/LogViewer#163]
Is it possible to have S3 as a storage for the logs? With my application running on a load balancer, I'd like logs from all instances to be in the same location.

Debugging issues is difficult when having to wait to get the right app instance with the error in the log.

**Comment by arcanedev-maroc** [comment]
I don't think it's possible with the current version.

Feel free to implement this feature with a PR 👍

**Comment by QConnect2** [comment]
I can`t find any solution for this issue 
laravel logger with load balancer

**Comment by QConnect2** [comment]
I have load balancer and 2 web apps 
how to make centralized laravel logs instead of log file on each web app
