### ISSUE TITLE
Open other monolog files

### ISSUE THREAD

**Issue by Ddiods** [ARCANEDEV/LogViewer#164]
I'll be great if it can read all monolog files in log folder. For example in the project where I'm working we have this files:

- laravel-Y-m-d.log
- email-Y-m-d.log
- scheduler-Y-m-d.log

Thanks!

**Comment by arcanedev-maroc** [comment]
Try to customize it with these [settings](https://github.com/ARCANEDEV/LogViewer/blob/master/config/log-viewer.php#L19-L23)

You can even create your own views/controllers to retrieve custom logs with [setPattern()](https://github.com/ARCANEDEV/LogViewer/blob/master/src/LogViewer.php#L127-L144) method

Keep in mind that you can interact with LogViewer as an API

**Comment by Ddiods** [comment]
Hi, 
Do you have an example or documentation about how to use it as an API?

Thanks!

**Comment by arcanedev-maroc** [comment]
The documentation is not available yet but you can check the tests folder.

Try: https://github.com/ARCANEDEV/LogViewer/blob/master/tests/LogViewerTest.php

**Comment by delmicio** [comment]
@arcanedev-maroc could you provide an example for pattern all .log files please.
```
'prefix'    => '*', 
'date'      => '*', 
'extension' => Filesystem::PATTERN_EXTENSION, // '.log'
```
This is not working for my file called `laravel-{RANDOMSTR}-2017-12-22.log`

**Comment by arcanedev-maroc** [comment]
See the comment: https://github.com/ARCANEDEV/LogViewer/issues/135#issuecomment-355037532
