### ISSUE TITLE
Custom storage-path is not working

### ISSUE THREAD

**Issue by bfuzze** [ARCANEDEV/LogViewer#165]
- LogViewer Version: 4.3.8
- Laravel Version: 5.4
- PHP Version: 5.6.24

### Description:
Unable to override the logs storage-path.

### Steps To Reproduce:
I've overridden the default log storage path by extending the LogServiceProvider.  Log's are generated as expected.

I changed the log-viewer config value for 'storage-path', but it is still looking in the old location.
Under the LogViewerController, I dump the config value for log-viewer.storage and confirmed it is the correct path.  I also dumped the config value returned ($config->get('log-viewer.storage-path')) under UtilitiesServiceProvider::registerFilesystem, but it is the old path.  In addition, when I overrode the location value here, the correct log files were displayed.   

It occurs to me this might be some sort of config load order issue.  I made sure the LogViewerServiceProvider is last in my app config and cleared caches, but no change.

Full disclosure:  I am new to Laravel, but not new to PHP or application development.  Maybe I'm configuring something wrong.  

I'm just getting started, but it looks like a really solid product.  Great work.
Thanks.

**Comment by arcanedev-maroc** [comment]
If you've changed the storage path for the logs by editing this [method in the `LogServiceProvider`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Log/LogServiceProvider.php#L77-L89). 

Can you tell us what path you've specified ? and also the path you're using in the `log-viewer.storage-path` ?

I need more information to reproduce the issue and see if i can help you as fast as i can.
