### ISSUE TITLE
Integrating ArcaneDev-LogViewer in Laravel-Backpack

### ISSUE THREAD

**Issue by eduardoarandah** [ARCANEDEV/LogViewer#167]
I modified ArcaneDev-LogViewer views to work with https://github.com/Laravel-Backpack/Base 

Might be of your interest

https://github.com/eduardoarandah/Laravel-Backpack-ArcaneDev-LogViewer

![xx](https://user-images.githubusercontent.com/4065733/29938257-cd848f5e-8e4d-11e7-89e1-604e352f158f.png)

**Comment by arcanedev-maroc** [comment]
😆 (nice meme). I ❤️ it, keep the good work.

Try to update the `show` view with the new **search** feature. Check the PR: #154

**Comment by eduardoarandah** [comment]
sure!

**Comment by eduardoarandah** [comment]
updated it to latest version

Please check my notes here. 
https://github.com/eduardoarandah/Laravel-Backpack-ArcaneDev-LogViewer#notes-on-how-i-did-it

There's only one conflict with a JQuery selector, if you make it compatible with JQuery 2.2.0, all files outside _template folder could go untouched

(Also added your logo in title)
![imagen](https://user-images.githubusercontent.com/4065733/30308421-06967950-974b-11e7-8129-66e41172baf6.png)
