### ISSUE TITLE
Hot Key

### ISSUE THREAD

**Issue by nyrik8989** [ARCANEDEV/LogViewer#168]
Next log page CTRL+→ /xor/  CTRL+←
CTRL + ⇵- select log
CTRL + Enter- view stack

Thank you)

**Comment by arcanedev-maroc** [comment]
You can submit a PR for this feature 👍

**Comment by bloggervista** [comment]
@arcanedev-maroc  I guess this will need a lot of work plus it may change core as we need to make many thing javascript friendly for such feature to work isn't it?

**Comment by vesper8** [comment]
I've had great luck using http://dmauro.github.io/Keypress/ to integrate hotkeys in my web apps. Works really well and easy to set up even with vue.js projects
