### ISSUE TITLE
easy way to remove the confirmation dialog on delete

### ISSUE THREAD

**Issue by vesper8** [ARCANEDEV/LogViewer#171]
love your package, use it all the time.

it would be nice if you could disable the confirmation dialog when hitting the delete icon

and for a future major version.. it would be great if the dashboard was a vue.js SPA and didn't need reloading

**Comment by arcanedev-maroc** [comment]
Try to override the default `views` & `controllers` for all your needs.

Check this response: https://github.com/ARCANEDEV/LogViewer/issues/83#issuecomment-249430860

I prefer to keep the `delete dialog` as the default.
