### ISSUE TITLE
Auth Protection for log viewer Laravel 5.5.13

### ISSUE THREAD

**Issue by umairali** [ARCANEDEV/LogViewer#174]
- LogViewer Version: 4.4
- Laravel Version: 5.5.13
- PHP Version: 7

**Comment by arcanedev-maroc** [comment]
Check this: https://github.com/ARCANEDEV/LogViewer/issues/69

And if you have any other question about this package, make sure to search in the previous closed issues or by the labels like this: [question](https://github.com/ARCANEDEV/LogViewer/issues?q=label%3Aquestion+is%3Aclosed)
