### ISSUE TITLE
Unable to view stack information

### ISSUE THREAD

**Issue by chjw8016** [ARCANEDEV/LogViewer#176]
- LogViewer Version: 4.4
- Laravel Version: 5.4
- PHP Version: 7.0

### Description:
Unable to view stack information

**Comment by arcanedev-maroc** [comment]
Can you show us how to reproduce the issue ?

**Comment by chjw8016** [comment]
@arcanedev-maroc 
I have a link here. You can see it
http://yd.gammainfo.com/log-viewer

**Comment by arcanedev-maroc** [comment]
I don't think so, if you visit this link: http://yd.gammainfo.com/log-viewer/logs/2017-10-20/error

The stack button is available if the entry has a stack content.

Source code: https://github.com/ARCANEDEV/LogViewer/blob/master/resources/views/show.blade.php#L123-L131

**Comment by chjw8016** [comment]
I got it! Thanks
