### ISSUE TITLE
Feature request: Mail driver log viewer

### ISSUE THREAD

**Issue by FernandoWahl** [ARCANEDEV/LogViewer#178]
### Description:
Hello
First of all, I'm sorry for my English.

The idea I had was to implement an email viewer for when the log driver is used:
`MAIL_DRIVER=log`

Today when an email goes to the log is as follows:

[Image 1](https://ibb.co/bYrukw)
[Image 2](https://ibb.co/bGsOdG)

**Comment by arcanedev-maroc** [comment]
Feel free to make a Pull Request 👍
