### ISSUE TITLE
CDN Assets

### ISSUE THREAD

**Issue by fridzema** [ARCANEDEV/LogViewer#179]
Hello,

First of all i would like to say, i really enjoy using your package! 
The only problem that i am facing is that the assets are sometimes very slow to load. Maybe it is just a server problem at one of the CDN providers. 
But why load in from a CDN anyway?

I prefer local assets, with precaution that i need to publish the assets. 
Maybe its an idea to make this optional or something?

Also an automatic refresh (option) seems a good addition to me.

**Comment by arcanedev-maroc** [comment]
You can now use a custom template with your own assets.

PR: #189
