### ISSUE TITLE
Can you please support PHP >= 5.6 ?

### ISSUE THREAD

**Issue by rajjanorkar** [ARCANEDEV/LogViewer#180]
Can you please support PHP 5.6 ? As this package support laravel 5.* versions then it will be good idea to support PHP >= 5.6. Thank You

**Comment by arcanedev-maroc** [comment]
The package is based on Laravel releases.

If you're using Laravel v5.5, the min PHP version is [7.0](https://github.com/laravel/laravel/blob/master/composer.json#L8)

For Laravel 5.4, the min PHP version is [5.6.4](https://github.com/laravel/laravel/blob/5.4/composer.json#L8)

So, try to match your laravel app (version) with the package version: https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#version-compatibility

**Comment by rajjanorkar** [comment]
@arcanedev-maroc Cool 

So happy, thanks for quick reply.
