### ISSUE TITLE
View distorted 

### ISSUE THREAD

**Issue by tonoslav** [ARCANEDEV/LogViewer#181]
- LogViewer Version: 4.4.1
- Laravel Version: 5.5.0
- PHP Version: 7.0.11

### Description:
When my log is really long, for example I base64_encode some data and there is that really long string
Than **level** col looks like this
Also I have to "scroll" to the right to see the whole string because of class table-responsive 

![image](https://user-images.githubusercontent.com/3399021/32662482-fcf2cfc0-c62a-11e7-9a67-f85523f91d05.png)

In **Header** col if you set into `<p>` tag for example
![image](https://user-images.githubusercontent.com/3399021/32662668-9c2e080c-c62b-11e7-9d99-b4723e84d113.png)

Everything is ok or at least better 
![image](https://user-images.githubusercontent.com/3399021/32662779-fa6bfeba-c62b-11e7-8ff3-3c9ad5ce5e04.png)

### Steps To Reproduce:
Log some really long string without spaces

**Comment by arcanedev-maroc** [comment]
Closed: #189
