### ISSUE TITLE
Remove multiple logs at once

### ISSUE THREAD

**Issue by tonoslav** [ARCANEDEV/LogViewer#185]
- LogViewer Version: 4.4.1

### Description:
Add checkbox as first column to choose which logs to select and than add some actions on the bottom (for now only Delete)
Maybe something like "Un/Select all" button too

**Comment by arcanedev-maroc** [comment]
Closed: #189

**Comment by mg-freelancer** [comment]
Can I work on this feature ?

**Comment by arcanedev-maroc** [comment]
Feel free to make a PR :+1:

**Comment by arcanedev-maroc** [comment]
Duplicated: #16
