### ISSUE TITLE
Selecting logs from menu does not work.

### ISSUE THREAD

**Issue by prabeshb** [ARCANEDEV/LogViewer#186]
- LogViewer Version: 4.3
- Laravel Version: 5.3
- PHP Version: 5.6.4

### Description:
I am able to get to the dashboard and can view the information without any issues. But when I click on the logs menu, I get a page not found error. The url http://127.0.0.1:8000/log-viewer/logs does not have a corresponding route? Should that be explicitly added in my routes? 

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/559019/35639598-b68886d0-0688-11e8-954f-bfdec30f5ae3.png)

![image](https://user-images.githubusercontent.com/559019/35639616-cafd1446-0688-11e8-9e1f-0fff12070fb2.png)

**Comment by arcanedev-maroc** [comment]
You need to install the correct version of this package.

For Laravel `v5.3` => use LogViewer `v4.2.*`

Check this for more details: https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#version-compatibility

**Comment by arcanedev-maroc** [comment]
I'm going to close this issue because i've just tested this package with laravel 5.3 and everything works.

**Comment by prabeshb** [comment]
yes, its working fine now. Thanks 

I had to change the Prefix and it worked like charm. 

Kudos to you. This is amazing package and very useful. Good job. I am loving it.

**Comment by arcanedev-maroc** [comment]
You're welcome 😄
