### ISSUE TITLE
How to configure in lumen

### ISSUE THREAD

**Issue by bharatvaggu** [ARCANEDEV/LogViewer#187]
Hi

How to configure in lumen. Please provide configuration steps.

Thanks,
Bharat

**Comment by arcanedev-maroc** [comment]
Sorry, but this package doesn't support lumen. 

Only Laravel projects

**Comment by lucenarenato** [comment]
Boa tarde, tem alguma previsão para funcionar no lumen?
Good afternoon, do you have any plans to work on the lumen?
