### ISSUE TITLE
Logs with ids

### ISSUE THREAD

**Issue by legreco** [ARCANEDEV/LogViewer#191]
Awesome package!
It is a feature request.
I would be interresting to log errors with ids and implement search by id functionnality in the log viewer.
Use case:
A user do something on the app
An error occur on the server
The error is logged with and id
The user see a message: "an error has occured in the application. Contact your admin with this code [uuid] "
The admin open log viewer and search the error via the error id

**Comment by arcanedev-maroc** [comment]
I think this feature is already implemented.

You just need to handle your errors, something like this:

```php
Route::get('log', function () {
    $uuid = Ramsey\Uuid\Uuid::uuid4()->toString();

    $info = "An error has occured in the application. Contact your admin with this code [$uuid]";

    Log::warning($info, [
        'code'    => 500,
        'message' => 'Put the exception message error here',
    ]);

    return $info;
});
```

> **NOTE:** To make easy to locate the error, add also a date in the info message [Y-m-d]
