### ISSUE TITLE
Filter by channel

### ISSUE THREAD

**Issue by matheusdallrosa** [ARCANEDEV/LogViewer#192]
- LogViewer Version: 4.5
- Laravel Version: 5.6
- PHP Version: 7.2.2

### Description:
 Is there any idea of a future feature to filter the logs by the channel? 
 In Laravel 5.6.* we are able to register multiple channels, so it would be useful.

**Comment by arcanedev-maroc** [comment]
I think this is impossible to achieve because there is no information of the channel in the log files.

BTW, the only supported channel is the `daily` driver.
