### ISSUE TITLE
LogViewer 4.5.1 Issues

### ISSUE THREAD

**Issue by HDVinnie** [ARCANEDEV/LogViewer#193]
- LogViewer Version: 4.5.1
- Laravel Version: 5.6.3
- PHP Version: 7.2

### Description:
I recently upgraded my application to Laravel 5.6.3 and PHP 7.2. All went smooth besides this package seems to have changed on me and doesn't work. The styling seems to have changed (Not BLUE nav anymore) and the logger shows nothing anymore even know there is a log file.

https://imgur.com/KpU9jIc

### Steps To Reproduce:
Use Laravel 5.6.3 and PHP 7.2?

**Comment by HDVinnie** [comment]
silly mistake my end.

**Comment by arcanedev-maroc** [comment]
This is a new theme is based on bootstrap v4. 

You can change it to an old version by editing this: https://github.com/ARCANEDEV/LogViewer/blob/master/config/log-viewer.php#L43

**Comment by poseso** [comment]
@HDVinnie I also get blank page with no logs, what was your mistake?
