### ISSUE TITLE
LogViewer 4.5.1 Blank Page

### ISSUE THREAD

**Issue by poseso** [ARCANEDEV/LogViewer#195]
- LogViewer Version: 4.5.1
- Laravel Version: 5.6.4
- PHP Version: 7.2.2

### Description:
I install the package and everything is installed correctly, but when I go to the dashboard or logs in the dashboard i get a blank page like this: https://imgur.com/KpU9jIc   and when i go to /log-viewer/logs
I dont see any logs even though i know they are there

### Steps To Reproduce:

- Install fresh laravel 5.6 installation
- composer require arcanedev/log-viewer
- php artisan log-viewer:publish

**Comment by arcanedev-maroc** [comment]
Related to https://github.com/laravel/framework/pull/23118 ?

Duplication: #193

**Comment by arcanedev-maroc** [comment]
I've just tested the package, everything works fine.

Did you followed the installation steps ?

Link: https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#application-requirements

**Comment by poseso** [comment]
Yes I did follow the installation steps, And https://github.com/laravel/framework/pull/23118  doesn't fix the blank page, I'm on Laravel 5.6.4 not 5.6.3 in 5.6.4 that fix is already there, so I guess is not related

**Comment by arcanedev-maroc** [comment]
OK this is what i did to test the package:

* Creating a fresh app: `composer create-project laravel/laravel fresh-laravel && cd fresh-laravel`
* Installing LogViewer package: `composer require arcanedev/log-viewer`
* Editing the `.env` file: `LOG_CHANNEL=daily`
* **OPTIONAL** Publishing the package: `php artisan log-viewer:publish`

To test the package, i edited the `routes/web.php` file to create some logs:

```php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    Log::info('This is info log');

    return view('welcome');
});
```

Hit a the home url a couple times to create logs: `http://localhost/fresh-laravel/public`

Then visit: `http://localhost/fresh-laravel/public/log-viewer`

**Comment by poseso** [comment]
I just made another clean install and I see it's working following the same steps, it's weird.  in the same 5.6.4 with the same php 7.2.2, thank you for your time

**Comment by arcanedev-maroc** [comment]
No problem, thanks for using this package :+1:
