### ISSUE TITLE
Restrict access of logviewer dashboard to admin only

### ISSUE THREAD

**Issue by rajjanorkar** [ARCANEDEV/LogViewer#197]
- LogViewer Version: 4.4
- Laravel Version:  5.5
- PHP Version:  7

### Description:
In my laravel setup i have users table and roles table in roles table i have 'admin' & 'user'

I can easily check logged in user is admin or user.

Now i am able to restrict the logviewer route to only logged in user, so only logged in users can see the dashboard of logviewer.

But to be more secure i want to restrict this logviewer dashboard to admin only.

Any idea how i can implement this?

**Comment by arcanedev-maroc** [comment]
Duplicate: #69

**Comment by ahadtaji21** [comment]
log-viewer access by all users, how it could be restrict by only admin.
'route'         => [
        'enabled'    => true,
        'attributes' => [
            'prefix'     => 'log-viewer',
           'middleware' => ['web', 'auth'],
        ],
    ],
i have roles in which Administrator, operator, viewer

this is my normal rout
Route::get('/dashboard',array(
        'uses'=>'App\Http\Controllers\DashboardController@index',
        'as' =>'dashboard',
        'middleware' => ['auth','roles'],
        'roles' => [Administrator, Operator, Viewer]
    )
);
