### ISSUE TITLE
ErrorException when install

### ISSUE THREAD

**Issue by hopewise** [ARCANEDEV/LogViewer#20]
When tried to install using :

    composer require "arcanedev/log-viewer:~3.0"

I got :
  
    [ErrorException]
      Declaration of Arcanedev\LogViewer\LogViewerServiceProvider::registerConfig() should be compatible with Arcanedev\Support\PackageServiceProvider::registerConfig($separator = '.')

Any idea?

**Comment by arcanedev-maroc** [comment]
Resolved : https://github.com/ARCANEDEV/LogViewer/pull/13

Try to update your `arcanedev/log-viewer` package to the latest version.
