### ISSUE TITLE
This log view is super slow in production with 7000 + records

### ISSUE THREAD

**Issue by rajjanorkar** [ARCANEDEV/LogViewer#201]
This log view is super slow in production with 7000 + records per day.

Server is 64 GB RAM, e5 processer 8 core.

logs are stored in file, my site is super fast, but as soon as i go to log-viewer opening log, switching pages etc so slow.

Is my configuration wrong or this plugin is not meant to handle huge log files?

**Comment by arcanedev-maroc** [comment]
Related: #21

I'm going to close this because it's duplicated, please post your comments in the previous issue.

Thanks
