### ISSUE TITLE
Logs from multiple servers

### ISSUE THREAD

**Issue by akgmeet** [ARCANEDEV/LogViewer#206]
Can you please implement multiple server and domain feature.

For example I have two domains:

example1.com
example2.com

example1.com hosted on 3 servers for example:

192.168.0.1
192.168.0.2
192.168.0.3

example2.com hosted on 2 servers for example:

192.168.0.4
192.168.0.5

**Comment by Livijn** [comment]
I am thinking about it like this:

1. Schedule a task to run daily (or whatever suits your needs)
2. This task uploads the log to S3 (`servername-2018-12-05.log`)
3. LogViewer retrieves logs from S3 and merges all servers

If you'd like a domain feature, just store the logs in `/domain.com/servername-2018-12-05.log`
