### ISSUE TITLE
Avoid loading whole log files into memory

### ISSUE THREAD

**Issue by judgej** [ARCANEDEV/LogViewer#21]
This package looks well thought-through and organised - looking forward to trying it out.

Now, every single other log viewer package I've seen starts by loading an entire log file into memory, then parsing it from there. When the log files get big, then it blows the memory limits and fails. This can be a big problem at those times when you really need to be able to view the logs.

So, does this package load whole log files into memory (in parsed or raw form)? Or can it extract a portion of a log file direct from disk based on the page options (e.g. retrieve just log entries N to N+m from a file)?

It strikes me also that the start of each log entry could be indexed by byte position, so a position in a file can be seeked very quickly. Even if only every 10th or 100th log entry were indexed, it would provide some starting points.

Anyway - this is mainly a question (and I have not found the bit where you actually open the file for reading yet, so I don't know the answer).

**Comment by arcanedev-maroc** [comment]
Yeah, i was thinking about this for a long time and i'm wondering about improving it.

The first solution i've recommended is to use a **daily log** system to avoid loading a big log files (I don't know why **laravel use the single log system as default**).

Note this package is going to load the log files if it's needed:
  * If you want all stats (log entries) for all logs files, it loads/parse all log files.
  * And if you want only stats (log entries) for a single log file, it's going to load one log file.

So, the real performance issue is gonna be when you want all stats about your log files (Load/parse all files).

How to improve this ??
  * Caching/Storing results of stats if the file is not modified ?
  * Limiting the loading of log files (Load files in a specific year, and the default is gonna be the current year) ?
  * Limiting the file size (max size) ?

And honestly, i've been waiting for feedbacks about performances issues in real/big projects and stress out the package.

For the time being, there is no performance issue, so far so good :smile: .

> **And the best part of this package is you can use it like an API**. For example, get all log files list without loading/parsing.

Thanks for your feedback :+1:.

**Comment by judgej** [comment]
So your assumption for now is that no log file will ever be too big to fit into memory, so no action is needed?

**Comment by arcanedev-maroc** [comment]
There will be an action. I've added this issue to the milestone, to think about it for the next release.

What do you think about this : Limiting the loading log files by year (current year / chosen year) ?

I'm optimistic that log files will not exceed the 200~400Mo in total (daily log system of course) in one year.

**Comment by judgej** [comment]
Log file size can blow all optimistic assumptions. It only takes something in a scheduler to go wrong and you can have a 200Mbyte log file in a day.

**Comment by arcanedev-maroc** [comment]
Yeah, there will be always an exception, that's why i need a real case to see how i'm going to solve it.

And i'm always open for any suggestions and PR.

**Comment by judgej** [comment]
The problem to solve here is to be able to *seek* to a specific error entry in the log, given that they are numbered sequentially, and any error entry could take up multiple lines. For that to be practical, the log files need to be indexed so the position of each entry (or at least a number of regular entries to split the log file up into chunks) is known.

That sorts out paging of straight forward log file listings, when *not* searching, i.e. pattern matching. When searching and paging, ideally you would want something more like a database, which *can* be done with logging in Laravel, but it is not ideal storing logs in a binary format.

**Comment by arcanedev-maroc** [comment]
Yeah, indexing the logs is a good idea (with levels, headers, size, last modification ... without the stack to make it lighter) and also using a caching system to verify each file (if modified, re-index and store it).

With this enhancement:

 * Keep the statistics up-to-date (automatically or manually).
 * Adding new features like searching with a keyword (#7).

I leave this issue open if anyone is interested to help us with a suggestion/PR.

**Comment by gr-jialeiwang** [comment]
hi

in my case, i only want to check recently log files for example today yesterday or last week
its will be helpful if i can set a date, today is 2016-11-07 so for example  i set the date to  2016-11-06 then the plugin loads yesterday(2016-11-06) and today(2016-11-07)’s log files for me,
and maybe it will not cost so many memory.

and my log have a lot of debug data in it and i can’t change log_level in config/app.php
because someone else will analytic the debug data.
and i am only use error and emergency data,
its will be helpful if i can filter the logs

**Comment by robganly** [comment]
I encountered this issue when I first installed the package.

I solved it initially by increasing the memory limit in php.ini then realised it was slow to load and my browser was stalling. The solution I chose was to switch my log from 'single' to 'daily' in Laravel config/app.php, as well as archiving the existing massive log file away from the logs folder (so it wouldn't be picked up by the code). This way of logging is actually better practice really as it makes them more manageable, searchable etc. 

Now that I have done this it works a treat. :)

**Comment by desh901** [comment]
I'm struggling with this due to a Web application that logs a lot, i'm wondering if you've made any progress or had some idea to work on. If i have some spare time i'd be happy to contribute in order to enhance logs file loading. This apart, great tool, saves tons of time :)

**Comment by arcanedev-maroc** [comment]
Unfortunately, i didn't came up with an optimal solution.

There are few options to minimize the logs in production environment:

 * Setting the minimum log level: https://github.com/laravel/laravel/blob/master/config/app.php#L125
 * Cleaning the old logs with `log_max_files`: https://laravel.com/docs/5.4/errors#log-storage

Hope this may helps you

And feel free to post a PR 👍

**Comment by judgej** [comment]
I've had this at the back of my mind for a few years, and the only conclusion I have reached is that indexes would only be practical if the log lines were logged to a database instead of flat files. If the files were simply paged, then an index of where each line starts would be simple enough to maintain. However, when filtering entries, a more sophisticated index is needed. Since this was raised in 2015, servers have got bigger and faster, and PHP 7.x has got more efficient with memory, so large log files are slightly less of a problem now. Maybe in 2021 I'll come up with a bright idea.

**Comment by judgej** [comment]
"just". Yes, `fgets()` can read lines in a file. There is more to it than that though. Paging, perhaps caching of the position of page numbers for a quick seek *without* the throughput of reading nearly the entire file every time a page is shown. And then filtering, possibly also with caching for the page start positions of each page within the context of a filter.

And now suppose your logging driver isn't the local file system? You won't even have `fgets()` to use then.

**Comment by jasonbronson** [comment]
Why not use this package for your needs?
https://github.com/bcremer/LineReader
