### ISSUE TITLE
Show all log files in log folder

### ISSUE THREAD

**Issue by tomswinkels** [ARCANEDEV/LogViewer#211]
- LogViewer Version: 4.5.1
- Laravel Version: 5.6.x
- PHP Version: 7.1

### Description:

For Laravel 5.6 i have create log files for only info about Facebook webhooks.

``` 
'WebhookFacebook' => [
 'driver' => 'daily',
 'path' => storage_path('logs/WebhookFacebook.log'),
 'level' => 'debug',
 'days' => 7,
],
```

At this moment i don't see that log file in the LogViewer.

Is there some option that we can see all the log files, or maybe some idea to implement?

**Comment by sentiasa** [comment]
Or imagine showing nginx errors there too :) Would be slick!

**Comment by arcanedev-maroc** [comment]
Feel free to make a PR for this feature :+1:

**Comment by yormy** [comment]
I have the feature to parse all laravel-log files ready, but the tests fail because the tests are hardcoded to find a name based on a given date. So it is impossible to pass the tests with filenames that do not contain the dates.

@arcanedev-maroc 
What is your suggestion ?
With the current tests in place , adding this parse-all feature would require alot of conditional code and new blades. My suggestion would be to make the test filename independent. Please advice on how to proceed

**Comment by arcanedev-maroc** [comment]
Hi @yormy,

Just keep in mind that the package only supports the `daily` log files. 

The reasons are:

* Small files (manageable to clean and delete)
* Better performance
* A built-in feature in laravel that auto delete the old log files: `log_max_files`

```
Source: https://laravel.com/docs/5.5/errors#log-storage

Maximum Daily Log Files
When using the daily log mode, Laravel will only retain five days of log files by default. 
If you want to adjust the number of retained files, you may add a log_max_files configuration 
value to your app configuration file:

'log_max_files' => 30
```

The PR you've sent in https://github.com/ARCANEDEV/LogViewer/pull/269 has major changes and it'will break the `daily` mode.

And it will breaks also the other user's projects:

* https://github.com/rappasoft/laravel-5-boilerplate
* https://github.com/adr1enbe4udou1n/laravel-boilerplate
* https://github.com/antaresproject/project
* https://github.com/eduardoarandah/backpacklogviewer
* [And more...](packagist.org/packages/arcanedev/log-viewer/dependents)

The only suggestion i can give is to try adding this feature without breaking the existed ones. 

If you think it's impossible, then the package can't support it.

**Comment by tomswinkels** [comment]
@yormy other thing what you can do is make some PR for Telescope. The logging of Telescope are very cool. But there you can't split up log files.

**Comment by yormy** [comment]
@arcanedev-maroc thanks for the clarification, I see what I can do

**Comment by yormy** [comment]
@tomswinkels  cool,,, I have not really looked into telescope yet. will do that too
