### ISSUE TITLE
Problem using middleware

### ISSUE THREAD

**Issue by jjpotestad** [ARCANEDEV/LogViewer#212]
- LogViewer Version: 4.4.2
- Laravel Version: 5.5.40
- PHP Version: 7.1.9

### Description:
I have a problem using middleware. If I write to the .env file 

`ARCANEDEV_LOGVIEWER_MIDDLEWARE=auth`

then it will not let me enter the log-viewer

### Steps To Reproduce:
1-) Install log-viewer
2-) configure log-viewer with route setting 
```php
'route'         => [
    'enabled'    => true,
    'attributes' => [
        'prefix'     => 'logging',
        'middleware' => env('ARCANEDEV_LOGVIEWER_MIDDLEWARE') ? explode(',', env('ARCANEDEV_LOGVIEWER_MIDDLEWARE')) : null,
    ],
],
```
3-) Write to the .env file
```
APP_LOG_LEVEL=info
APP_LOG=daily
ARCANEDEV_LOGVIEWER_MIDDLEWARE=auth
```

**Comment by arcanedev-maroc** [comment]
You've changed the route **prefix**. Did you check this URL: `http://your-project.test/logging`

**NOTE:** You've installed an incorrect version, check this section https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#version-compatibility

**Comment by jjpotestad** [comment]
I can access to the log-viewer using the prefix logging if I don't write any Middleware in the .env file. My problem is when I write for example ARCANEDEV_LOGVIEWER_MIDDLEWARE=auth
I need to use a Middleware for this route.

I think I installed the right version 4.4.* on Laravel 5.5.* 

I'm using Windows 10, may be a problem?

**Comment by arcanedev-maroc** [comment]
Can you test it in a fresh laravel because i can't reproduce the issue.

Try also to clear the config cache: `php artisan config:clear`.

**Comment by jjpotestad** [comment]
Now I try in a fresh laravel and i have the same problem.

After execute php artisan make:auth and create a user, a write ARCANEDEV_LOGVIEWER_MIDDLEWARE=auth on .env and I can't access to log-viewer. I can access only if I remove the Middleware.

Are you sure you can't reproduce the issue?

**Comment by arcanedev-maroc** [comment]
When you say you **can't access** the log-viewer, you get the **login form** instead ??

If Yes, it's the intended behavior

**Comment by jjpotestad** [comment]
Solved, when I use the middleware I have to put ARCANEDEV_LOGVIEWER_MIDDLEWARE = web, auth, mymiddleware, etc.
if I use alone
ARCANEDEV_LOGVIEWER_MIDDLEWARE = auth
so what I said to you happens.
Thanks for your help. Awesome work, i love it
