### ISSUE TITLE
Log viewer doesn't work well with long first lines

### ISSUE THREAD

**Issue by francislavoie** [ARCANEDEV/LogViewer#215]
- LogViewer Version: 4.4.2
- Laravel Version: 5.5.40
- PHP Version: 7.2.5

### Description:
Table rendering when viewing logs doesn't work well with the default CSS if there's really long strings at the end of the first line. This is the case when using something like `\Log::debug("some string", ["additional" => "data"]);`, i.e. the 2nd arg being JSON encoded before written to logs.

The "Level" column ends up wrapping, and the "Header" column becomes very wide (requiring horizontal scrolling to get to the end).

I think the solution would be to mess around with word wrap and whitespace CSS properties to make it a bit more reliably rendered.

### Steps To Reproduce:
Just output some long JSON to logs then view it in a narrow browser window.

**Comment by arcanedev-maroc** [comment]
Feel free to make a PR :+1:
