### ISSUE TITLE
local.ERROR: Call to a member function send() 

### ISSUE THREAD

**Issue by testdnmedia** [ARCANEDEV/LogViewer#216]
- LogViewer Version: dev & 4.5.1
- Laravel Version: 5.6.26
- PHP Version: PHP 7.1.14 

why every time you open the logs-system page always add error ?

Header : 
Call to a member function send() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function send() on null at /public_html/laravel/index.php:58)

local.ERROR: Call to a member function send() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function send() on null at /public_html/laravel/index.php:58)
[stacktrace]
#0 {main}
"}

**Comment by arcanedev-maroc** [comment]
I think this is unrelated to the package because there is no `send()` in this package. 

You need to check you laravel project.
