### ISSUE TITLE
intercetp error 404

### ISSUE THREAD

**Issue by maxdiable** [ARCANEDEV/LogViewer#217]
- LogViewer Version: 4.5.1
- Laravel Version: 5.6.26
- PHP Version: 7.2.25

it's possible intercept request errors: 404, 500 ecc... ??

br
max

**Comment by arcanedev-maroc** [comment]
Check the documentation: https://laravel.com/docs/5.6/errors

Or ask/search your question in the forums (Laracasts, ...)
