### ISSUE TITLE
Parsing "Context" of Logs

### ISSUE THREAD

**Issue by fzyzcjy** [ARCANEDEV/LogViewer#220]
- LogViewer Version: 4.5.1
- Laravel Version: 5.6
- PHP Version: 7.1

### Description:

Hello! Thank you for your wonderful job of creating this package!
Monolog has a powerful function that we can not only log a string (message), but also some object called "context" (and another "extra"). It can be seen here: https://github.com/Seldaek/monolog/blob/master/doc/01-usage.md . Therefore, I think it would be great if this package can parse the context and extra JSON object, and display them in separate columns to increase the user experience. In my thoughts, a JsonFormatter (instead of the default LineFormatter) will log all those things into one json, so it will be very easy for the parser to do the job.

p.s. I can make a pull request about this if you are busy and have no time implementing this feature.

**Comment by arcanedev-maroc** [comment]
Hi @turtlegood,

Feel free to make a PR and don't forget the tests :+1:

**Comment by turtlegood** [comment]
@arcanedev-maroc OK I will try my best

**Comment by turtlegood** [comment]
I have tried my best to read the source code, and I really appreciate the elaborated structure of the project. However, I find it difficult to add this feature into this existing code structure. Therefore, I am sorry that I cannot help to make a pull request...
