### ISSUE TITLE
Paginate does not work

### ISSUE THREAD

**Issue by Gil-1** [ARCANEDEV/LogViewer#221]
- LogViewer Version: 4.5.1
- Laravel Version: 5.6
- PHP Version: 7.2

### Description:

I have the error "Page not found" if I'm on a certain log level or "The list of logs is empty!" on the "All" levels.

### Steps To Reproduce:

I have a log file of 30 mb. 
Laravel log is not configured on daily (I have a single log file : laravel.log).
I had to rename it as this : laravel-2018-07-12.log to make it work.
I don't see any option to make "laravel.log" work in config/log-viewer.php

Let me know if I can help

**Comment by arcanedev-maroc** [comment]
Is not going to work normally by just renaming the file because the the content is not valid, it will contain all the dates/hours of the `single` log system.

Try to set the logviewer properly (delete also the old logs) and see if the issue is persisting.

**Comment by ahadtaji21** [comment]
arcanedev logviewer pagination icon twice
