### ISSUE TITLE
Menu display language different from config

### ISSUE THREAD

**Issue by sysoce** [ARCANEDEV/LogViewer#222]
- LogViewer Version: 4.4.2
- Laravel Version: 5.5
- PHP Version: 7.1.17

### Description:
The menu in the log view does not display the language set in log-viewer config but defaults to the app locale.

### Steps To Reproduce:
1. Make sure the Laravel app locale is different than the locale set in log-viewer config to be able to see the bug.
2. Open the log viewer, e.g. navigate to /log-viewer/logs/[log-name]

### Suggested Fix
Do not change the locale inside the [get](https://github.com/ARCANEDEV/LogViewer/blob/master/src/Utilities/LogLevels.php#LC163) method in the [Arcanedev\LogViewer\Utilities\LogLevels](https://github.com/ARCANEDEV/LogViewer/blob/master/src/Utilities/LogLevels.php#LC163) class, but let the user of the class change the locale with the mutator if needed.

In [Arcanedev\LogViewer\Utilities\LogLevels](https://github.com/ARCANEDEV/LogViewer/blob/master/src/Utilities/LogLevels.php#LC163) change line 165 in the [get](https://github.com/ARCANEDEV/LogViewer/blob/master/src/Utilities/LogLevels.php#LC163) method:
`$locale = $locale ? $locale : $this->getLocale();`

This ensures the locale passed as an argument only applies to that function call and does not persist. If no locale is passed the locale will be retrieved as per usual with the getter. 

Other than that, thank you for this great package!

**Comment by arcanedev-maroc** [comment]
Hi @sysoce, thanks for using this package :+1: 

Try to update your project/packages and see if the issue was solved
