### ISSUE TITLE
Logs are being deleted!

### ISSUE THREAD

**Issue by mislam** [ARCANEDEV/LogViewer#224]
- LogViewer Version: 4.3.10
- Laravel Version: 5.4
- PHP Version: 7.2.7

### Description:

I just noticed on our production server today (July 23, 2018), all 4 older logs (2 days and older) are deleted (zero byte files), and probably archived.

Take a look at the browser screenshot:

![screen shot 2018-07-23 at 1 37 05 pm](https://user-images.githubusercontent.com/508043/43096333-5f797d4e-8e7e-11e8-8beb-1326837f22b8.png)

And also look at the files on logs folder (from server's terminal):

![screen shot 2018-07-23 at 1 33 46 pm](https://user-images.githubusercontent.com/508043/43096364-7bf8b3ae-8e7e-11e8-830f-d701ce2f6feb.png)

How did this happen? Is LogViewer erasing all logs from the files while archiving them?
Notice that the chmod also changed from 644 to 755 for those zero-byte files.

**Comment by arcanedev-maroc** [comment]
I don't think this is related to the package because it can't delete the content without deleting the file.

You need to change your app or your server setup.
