### ISSUE TITLE
API document needed

### ISSUE THREAD

**Issue by jkhaoqi110** [ARCANEDEV/LogViewer#227]
- LogViewer Version: 4.5.2
- Laravel Version: 5.6
- PHP Version: 7.1.3

### Description:
Thank you for offering this wonderful package!

In fact, I write my own spa by using laravel api, and I want to add this package to my application for analysing the application's logs, but the document here is incomplete, how can I use LogViewer only as an API.

Thank you very much!

**Comment by arcanedev-maroc** [comment]
You can start by browsing the `Contracts` folder, something like: https://github.com/ARCANEDEV/LogViewer/blob/master/src/Contracts/LogViewer.php

You can also read the default controller/routes, it covers all the basic features.

Or the tests folder for more examples.
