### ISSUE TITLE
Load from several folders and prefixes

### ISSUE THREAD

**Issue by curunoir** [ARCANEDEV/LogViewer#228]
- LogViewer Version: 4.5
- Laravel Version: 5.6
- PHP Version: 7.2

### Description:
Hello, Laravel 5.6 new logging system allow us to create some custom logs. So I create several log files in my projects which I organize into some subfolders in standard log path such as :
- storage/logs/laravel-2018-01-01.log
- storage/logs/folder1/customlog1-2018-01-01.log
- storage/logs/folder2/customlog2-2018-01-01.log

It would be a nice feature if LogViewer could handle multiple storage paths and logs prefixes. Maybe some wildcard in path and prefix config variables could handle it. Or inspecting the logs channels in the new **config/logging.php** Laravel config file could help LogViewer to automatically handle custom logs locations. :)

**Comment by arcanedev-maroc** [comment]
Duplicated: #70
