### ISSUE TITLE
Log more than five days

### ISSUE THREAD

**Issue by shareef1989** [ARCANEDEV/LogViewer#229]
- LogViewer Version: 4.3.9
- Laravel Version: 5.5.42
- PHP Version: 7.1.14

### Description:
I want to get logs for more than 5 days
currently, log viewer saves only last five log files
is there a config or a way to solve it?

**Comment by arcanedev-maroc** [comment]
This is related to laravel. Check the official documentation, especially [this section: Log Storage - Maximum Daily Log Files](https://laravel.com/docs/5.5/errors#log-storage)

**Comment by apair** [comment]
in Laravel >5.6 you can increase daily log limitation in  `/config/loggin.php > daily > days `
