### ISSUE TITLE
Installation error on laravel 5.6

### ISSUE THREAD

**Issue by dels07** [ARCANEDEV/LogViewer#232]
- LogViewer Version: 4.6.0
- Laravel Version: 5.6.35
- PHP Version: 7.1.16

### Description:
Unable to install package due to **arcanedev/support** require:
"illuminate/filesystem": "~5.7.0",
"illuminate/support":    "~5.7.0"

Currently solved by adding composer entries manually for old version
"arcanedev/log-viewer": "4.5.*"

> Problem 1
    - arcanedev/log-viewer 4.6.0 requires arcanedev/support ~4.4.0 -> satisfiable by arcanedev/support[4.4.0].
    - Installation request for arcanedev/log-viewer ^4.6 -> satisfiable by arcanedev/log-viewer[4.6.0].
    - Conclusion: remove laravel/framework v5.6.35
    - Conclusion: don't install laravel/framework v5.6.35
    - arcanedev/support 4.4.0 requires illuminate/filesystem ~5.7.0 -> satisfiable by laravel/framework[5.7.x-dev], illuminate/filesystem[5.7.x-dev,
v5.7.0, v5.7.1].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.6.35].
    - don't install illuminate/filesystem 5.7.x-dev|don't install laravel/framework v5.6.35
    - don't install illuminate/filesystem v5.7.0|don't install laravel/framework v5.6.35
    - don't install illuminate/filesystem v5.7.1|don't install laravel/framework v5.6.35
    - Installation request for laravel/framework (locked at v5.6.35, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.35].

### Steps To Reproduce:
composer require arcanedev/log-viewer

**Comment by arcanedev-maroc** [comment]
Check this section: https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md

**Comment by KinG-InFeT** [comment]
hi @arcanedev-maroc , i not undestand why the fix

**Comment by arcanedev-maroc** [comment]
Hi @KinG-InFeT, you need to install the correct version.

For example: 

Install the LogViewer `v4.4` if you're using Laravel `v5.5` by running this command `composer require arcanedev/log-viewer:4.4.0` or updating your `composer.json` file.

**Comment by madacol** [comment]
Why doesn't composer try to install the correct version?

**Comment by arcanedev-maroc** [comment]
@madacol i think when run `composer require arcanedev/log-viewer` (for example), composer try to install the latest version by default.

I think this is the excepted behavior because you specify a version.
