### ISSUE TITLE
Class 'Arcanedev\Support\Collection' not found on Laravel 5.5

### ISSUE THREAD

**Issue by craigward** [ARCANEDEV/LogViewer#235]
- LogViewer Version: 4.4
- Laravel Version: 5.5
- PHP Version: 7.1

Adding the package to my app gives the following error.

`Class 'Arcanedev\Support\Collection' not found` and I can't seem to get past it. I've followed the instructions to make sure I am installing the correct version but i'm at a loss.

**Comment by arcanedev-maroc** [comment]
Sorry, but i can't reproduce your issue.

For **Laravel v5.5**, make sure you have the correct version in your `composer.json` file: `"arcanedev/log-viewer": "~4.4.0"`

And run `composer update`

**Comment by craigward** [comment]
I've just add `"arcanedev/log-viewer": "~4.4.0"` as it was set at `"arcanedev/log-viewer": "4.4"`

Ran `composer update`

I can see 
`- Updating arcanedev/log-viewer (4.4.0 => 4.4.3): Downloading (100%)` 

but when I visit the `log-viewer` page I get the same `Class 'Arcanedev\Support\Collection' not found` error.

Is there anything else I can check?

**Comment by arcanedev-maroc** [comment]
Send me your `composer.json` file and i'm going to see how i can help you.

Can you reproduce the same issue in a fresh laravel application (Note the steps for us) ?

**Comment by arcanedev-maroc** [comment]
You're not

**Comment by arcanedev-maroc** [comment]
With your current `composer.json` dependencies, you're not using the correct laravel version.

Run: `php artisan --version`

**Comment by progsmile** [comment]
I'm having this error on 
- Laravel: 5.8.38
- Package version: "arcanedev/log-viewer": "4.4.5"

I dig into sources and couldn't found this class too. Need your help

**Comment by progsmile** [comment]
Reinstalled package to 4.7, now it's ok!
