### ISSUE TITLE
Log Viewer Empty

### ISSUE THREAD

**Issue by mikeerickson** [ARCANEDEV/LogViewer#238]
- LogViewer Version: 4.6
- Laravel Version: 5.7
- PHP Version: 7.2.7

### Description:

I have a simple log file, but it is not displaying anything when I access viewer

![image](https://user-images.githubusercontent.com/183153/46260739-b2e48e00-c49e-11e8-9c42-c7cc01924526.png)

![image](https://user-images.githubusercontent.com/183153/46260760-e7f0e080-c49e-11e8-80a7-fa798a519ddc.png)

**Comment by arcanedev-maroc** [comment]
please read carefully the documentation: https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#application-requirements
