### ISSUE TITLE
Problem with big logs

### ISSUE THREAD

**Issue by CristhianUNSa** [ARCANEDEV/LogViewer#241]
- LogViewer Version: 4.1.0
- Laravel Version: 5.2
- PHP Version: 7.0

### Description:
Logs greater than X MB will produce http 500 error (X > 8)

### Steps To Reproduce:
Just log a good amount of logs one day, and it will show the error.

### Workaround
Deleting big log files will show LogViewer page again

**Comment by CristhianUNSa** [comment]
I had this problem again with an even smaller log. I will show you a screenshot:
![image](https://user-images.githubusercontent.com/12214429/46744965-868cf680-cc82-11e8-9ddf-e76bd13aa9f0.png)

**Comment by arcanedev-maroc** [comment]
You can fix your issue by increasing the PHP memory:

Change the line in `php.ini` If your line shows 32M (try 64M for example): `memory_limit = 64M`

You can extend it to 1024M if you have the resources on your machine.

**Comment by komarnicki** [comment]
This absolutely doesn't help. I also logged a 300 MB of data into logs and the package just crashed `Allowed memory size of 536870912 bytes exhausted`. Increasing resources is just a temporary solution IMHO. This package is part of `laravel-5-boilerplate`. Probably I will end up disabling this…

**Comment by arcanedev-maroc** [comment]
Hi @komarnicki, 

How did you get 300 MB of data into logs ? Is that in **dev** or **production** environment ?

Feel free to disable the log-viewer if it doesn't helps you.

You can also make a PR to fix the issue and help others :+1:
