### ISSUE TITLE
Protect user password from the log files

### ISSUE THREAD

**Issue by Manjul-Nexio** [ARCANEDEV/LogViewer#250]
- LogViewer Version: 4.6.2
- Laravel Version: 5.7
- PHP Version: 7.2

### Description:
I am logging every request and resposnse as describe in this link https://gist.github.com/Shelob9/174f6093c6b388f325157ba3dea82a46.
The problem is that its also showing the users password. How do i protect it from getting logged ?

### Steps To Reproduce:
laravel new <project name>
composer require arcanedev/log-viewer
create a middleware named LogAfterRequest
paste the code form this link in the "LogAfterRequest" middleware
register the middleware in the kernel.php file under 'protected $middleware'
make auth using laravel artisan command. login into the application.
check the logs and search for the password you entered

**Comment by arcanedev-maroc** [comment]
Try something like this:

```php
<?php namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Log;

class LogAfterRequest
{
    protected $except = [
        '_token',
        'password',
        'password_confirmation',
        //...
    ];

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Closure                   $next
     *
     * @return mixed
     */
    public function handle($request, Closure  $next)
    {
        return $next($request);
    }

    /**
     * @param  \Illuminate\Http\Request   $request
     * @param  \Illuminate\Http\Response  $response
     */
    public function terminate($request, $response)
    {
        Log::info('app.requests', [
            'request'  => $request->except($this->except),
            'response' => $response
        ]);
    }
}
```

Next time, try to ask the forums because your question is not related to this package.
