### ISSUE TITLE
possibility delete a single file log

### ISSUE THREAD

**Issue by KinG-InFeT** [ARCANEDEV/LogViewer#256]
- LogViewer Version: latest
- Laravel Version: 5.6
- PHP Version: 7.2

### Description:
can i delete single log file from UI

**Comment by arcanedev-maroc** [comment]
If you're using the `daily` log files then yes, you can delete the logs individually

**Comment by KinG-InFeT** [comment]
Yes i undestand but i have other log files not only laravel log , can i deteled it in single mode?
