### ISSUE TITLE
Need way to add custom menu items

### ISSUE THREAD

**Issue by maxvaser** [ARCANEDEV/LogViewer#257]
- LogViewer Version: latest
- Laravel Version: latest
- PHP Version: 7.2.x

### Description: There is no way to add custom menu items so that it's easy to get back to other parts of the site, like the main admin section. this would be a very helpful enhancement. 

P.S. This is a really great package! Very useful.

**Comment by Traqza** [comment]
You have to edit the resource master file for the layout. I was able to get everything setup to same as the rest of my application in a few minutes.
