### ISSUE TITLE
Better middleware support

### ISSUE THREAD

**Issue by rappasoft** [ARCANEDEV/LogViewer#26]
I have middleware set in the config file, but is there anyway to set a redirect instead of just an Unauthorized message?

**Comment by arcanedev-maroc** [comment]
Hi rappasoft,

As i said before, the routes/controllers/views are just for demo purpose, i've always recommend to use LogViewer as API.

I don't know what you mean by `a better middleware support`. But if you have a suggestion or example, please let me know.

BTW you can override everything that are not suitable for you project. 

The easy way to do that:
  * Disable the default LogViewer routes by setting [this line to false](https://github.com/ARCANEDEV/LogViewer/blob/master/config/log-viewer.php#L23).
  * Copy/Paste all routes from [LogViewerRoute](https://github.com/ARCANEDEV/LogViewer/blob/master/src/Http/Routes/LogViewerRoute.php) and edit it as you want (Setting up your middleware, custom controllers ...).

**Comment by rappasoft** [comment]
That worked thank you.

**Comment by arcanedev-maroc** [comment]
Nice :+1:

**Comment by fmarkos** [comment]
Hey great package!
I use zizaco/entrust package to setup roles etc.
and I added this to .env :
ARCANEDEV_LOGVIEWER_MIDDLEWARE=web,auth,**role:admin**
it works fine and only admins can see /log-viewer/logs
simple users, managers, etc. are redirected.
