### ISSUE TITLE
uninstall issue with Laravel

### ISSUE THREAD

**Issue by loadwolf** [ARCANEDEV/LogViewer#263]
- LogViewer Version:  "arcanedev/log-viewer": "^4.6",
- Laravel Version: 5.8.*",
- PHP Version: "^7.1.3",

### Description:
When attempting to uninstall the library from Laravel with it shows the following error:
-------------------------------------------------------------------------

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

>In log-viewer.php line 20:

>  Class 'Arcanedev\LogViewer\Contracts\Utilities\Filesystem' not found

>Script @php artisan package:discover --ansi handling the post-autoload-dump event returned >with error code 1
>sp@sp:/var/www/html/mqpr$ php artisan log-viewer:clear

>In log-viewer.php line 20:

>  Class 'Arcanedev\LogViewer\Contracts\Utilities\Filesystem' not found

---------------------------------------------------------------------

### Steps To Reproduce:

run "composer update" on  a project that previously had ""arcanedev/log-viewer":" installed on Laravel.

adding "arcanedev/log-viewer" back to the composer.json removes the error and Laravel runs as normal, but it is extra code that is not longer needed for this project.

# NOTE
Similar but slightly different issue as one on stackoverflow that is as yet unanswered (Same process to discover the issue and the same error message, his was updating mine removing)
https://stackoverflow.com/questions/48152826/arcanedev-logviewer-contracts-utilities-filesystem-not-found

**Comment by arcanedev-maroc** [comment]
You have two options to solve this.

**Solution 1:**

* Delete the `log-viewer.php` config file in your production env.

**Solution 2:**

* Replace the `constants` with the commented values:

```php
return [
    //...

    'pattern'       => [
        // 'prefix'    => Filesystem::PATTERN_PREFIX,    // 'laravel-'
        // 'date'      => Filesystem::PATTERN_DATE,      // '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
        // 'extension' => Filesystem::PATTERN_EXTENSION, // '.log'

        'prefix'    => 'laravel-',
        'date'      => '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]',
        'extension' => '.log',
    ],

    //...
];
```

**Comment by MusheAbdulHakim** [comment]
I have the same issue with laravel 8.
This is the command i used to install it `composer require arcanedev/log-viewer:8.x`
This is the command i am using trying to remove it `composer require arcanedev/log-viewer:8.x`
 and this what am getting in the terminal.
`arcanedev/log-viewer: is not required in your composer.json and has not been removed
8.x is not required in your composer.json and has not been removed
./composer.json has been updated
Running composer update arcanedev/log-viewer: 8.x
Loading composer repositories with package information
Package "arcanedev/log-viewer:" listed for update is not locked.
Package "8.x" listed for update is not locked.
`
