### ISSUE TITLE
Didn't work with Laravel entrust middleware 

### ISSUE THREAD

**Issue by usmansaif** [ARCANEDEV/LogViewer#264]
- LogViewer Version: 4.6.7
- Laravel Version: 5.7
- PHP Version: 7.2.15

### Description:
I tried to add logviewer with implemented role and permissions package laravel entrust.

I tried to add middleware
'middleware' => ['role:root,admin'];
I got error 403 

Please advice me 
### Steps To Reproduce:
1. install laravel
2. install laravel entrust package
3. install laravel logviewer
4. update middleware configurations (defined as above)
5. got error 403

**Comment by arcanedev-maroc** [comment]
This is not related to this package, please follow the installation/configuration steps in `zizaco/entrust`.

This is why you get 403 error: https://github.com/Zizaco/entrust/blob/master/src/Entrust/Middleware/EntrustRole.php#L44-L46
