### ISSUE TITLE
Middleware issue

### ISSUE THREAD

**Issue by robertnicjoo** [ARCANEDEV/LogViewer#267]
- LogViewer Version: 4.7
- Laravel Version: 5.8
- PHP Version: 7.3

### Description:
I have custom middleware and it doesn't work with this package

### Steps To Reproduce:
This is what i use in my route file `web.php`

```php
Route::prefix('/admin')->middleware(['role:Admin|Editor|Customer', 'verified'])->group(function () {
  //my routes
});
```

Now If I want use same middleware with this package it will be like:

```php
ARCANEDEV_LOGVIEWER_MIDDLEWARE=role:Admin,verified
```
and this will return `403` error only for log-viewer url's rest of my site works just fine as the result of my account being verified, logged in, and having admin role.

## Question

How can I use my middleware with this package?

### Note
I am using https://github.com/spatie/laravel-permission for my roles and permissions.

**Comment by arcanedev-maroc** [comment]
Try to add the `web` middleware

```
ARCANEDEV_LOGVIEWER_MIDDLEWARE=web,role:Admin,verified
```

https://github.com/ARCANEDEV/LogViewer/issues?utf8=✓&q=is%3Aissue+middleware
