### ISSUE TITLE
Usage: What to log. How to log.

### ISSUE THREAD

**Issue by alagoroVigo** [ARCANEDEV/LogViewer#278]
- LogViewer Version: newst
- Laravel Version: 5.8.33
- PHP Version: 7.2

### Description:
In Usage documentation, please show usage example of how to set different log levels and how to log so messages go to different log levels

**Comment by arcanedev-maroc** [comment]
Check Laravel [documentation](https://laravel.com/docs/5.8/logging#writing-log-messages) about the logging
