### ISSUE TITLE
Route [log-viewer::dashboard] not defined

### ISSUE THREAD

**Issue by lloricode** [ARCANEDEV/LogViewer#297]
- LogViewer Version: 5.1.1
- Laravel Version: 6.1.0
- PHP Version: 
```
PHP 7.2.22-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.22-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

```

### Description:
Hi! it give me error after updating latest log-viewer

![Screenshot from 2019-10-03 08-45-03](https://user-images.githubusercontent.com/8251344/66091442-5d175a00-e5ba-11e9-8177-888a5b029422.png)

![Screenshot from 2019-10-03 08-47-47](https://user-images.githubusercontent.com/8251344/66091471-7f10dc80-e5ba-11e9-873b-0bd0304fbf2d.png)

### Steps To Reproduce:

update log-viewer, then visit the site with calling route

run also ` php artisan log-viewer:publish --force` and nothing happen

**Comment by arcanedev-maroc** [comment]
Hi @lloricode, thanks for reporting this bug.

Try to update your project and see if the issue is fixed.

Don't forget to delete the cached files in `bootstrap/cache/*.php`.

And thanks for using the package :+1:

**Comment by lloricode** [comment]
@arcanedev-maroc thanks, ill check
