### ISSUE TITLE
Error on publishing config

### ISSUE THREAD

**Issue by SerendipityNL** [ARCANEDEV/LogViewer#3]
After installing the LogViewer with composer I wanted to publish the configs but I got the following error:

    vagrant@homestead:~/projects/mt$ php artisan vendor:publish --provider="Arcanedev\LogViewer\LogViewerServiceProvider" --force
    PHP Fatal error:  Access level to Arcanedev\LogViewer\LogViewerServiceProvider::registerConfig() must be protected (as in class Arcanedev\Support\Laravel\PackageServiceProvider) or weaker in /home/vagrant/projects/mt/vendor/arcanedev/log-viewer/src/LogViewerServiceProvider.php on line 12
    PHP Stack trace:
    PHP   1. {main}() /home/vagrant/projects/mt/artisan:0
    PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/vagrant/projects/mt/artisan:36
    PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/vagrant/projects/mt/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:98
    PHP   4. Illuminate\Foundation\Application->bootstrapWith() /home/vagrant/projects/mt/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:206
    PHP   5. Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap() /home/vagrant/projects/mt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:203
    PHP   6. Illuminate\Foundation\Application->registerConfiguredProviders() /home/vagrant/projects/mt/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:17
    PHP   7. Illuminate\Foundation\ProviderRepository->load() /home/vagrant/projects/mt/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:507
    PHP   8. Illuminate\Foundation\ProviderRepository->compileManifest() /home/vagrant/projects/mt/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:60
    PHP   9. Illuminate\Foundation\ProviderRepository->createProvider() /home/vagrant/projects/mt/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:114
    PHP  10. spl_autoload_call() /home/vagrant/projects/mt/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:146
    PHP  11. Composer\Autoload\ClassLoader->loadClass() /home/vagrant/projects/mt/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:146
    PHP  12. Composer\Autoload\includeFile() /home/vagrant/projects/mt/vendor/composer/ClassLoader.php:301
    PHP  13. include() /home/vagrant/projects/mt/vendor/composer/ClassLoader.php:412

      [Symfony\Component\Debug\Exception\FatalErrorException]
      Access level to Arcanedev\LogViewer\LogViewerServiceProvider::registerConfig() must be protected (as in class Arcanedev\Support\Laravel\PackageServiceProvider) or weaker

Setting the registerConfig function to protected fixed the issue.

**Comment by arcanedev-maroc** [comment]
Try to update the LogViewer to v2.12.4
