### ISSUE TITLE
Potential XXS vulnerability in search feature

### ISSUE THREAD

**Issue by blorange2** [ARCANEDEV/LogViewer#301]
- LogViewer Version: 4.5.3
- Laravel Version: 5.6.28
- PHP Version: 7.3.10

### Description:

I recently had a PenTest carried out and it came back in the report that the log viewer search functionality is vulnerable to XSS attack

### Steps To Reproduce:

1. Go to LogViewer
2. Perform a search within a specific log entry like so:

GET /thanos/log-viewer/logs/2019-10-03/error/search?query=%22%3E%3Cimg+src%3Dasdf+onerror%3Dalert%28document.cookie%29%3E

3. The JavaScript alert will trigger

**Comment by arcanedev-maroc** [comment]
Hi @blorange2,

Feel free to make a PR to fix this issue :+1:

**Comment by blorange2** [comment]
Hi again, 

Do you use any Laravel specific code standards or can it use vanilla PHP?

**Comment by arcanedev-maroc** [comment]
Mostly laravel standard

**Comment by blorange2** [comment]
@arcanedev-maroc I have a slightly out of scope question. So I forked the repository, cloned it and then checked out branch v4.5. 

Ideally, I'd like to test this within my current Laravel installation so I added this to my `composer.json` however it does not get acknowledged.

```

    "repositories": [{
        "type": "path",
        "url": "../../forks/LogViewer"
    }]

```

**Comment by blorange2** [comment]
@arcanedev-maroc so... it took me a while but I've got my local branch running with my project, I've had a look and we could probably just escape the input in the view?

Is there a reason it's currently unescaped in the show blade?

**Comment by arcanedev-maroc** [comment]
Hi @blorange2, sorry for the late response, i didn't see your comment.

I don't think there is a good reason for an unescaped value in the blade view.

**Comment by blorange2** [comment]
So, if I test adequately could I just escape the query string inside the view?

**Comment by arcanedev-maroc** [comment]
Go ahead, you can change `{!! $query !!}` into `{{ $query }}`

**Comment by arcanedev-maroc** [comment]
Correct, Laravel `v5.6` => LogViewer `v4.5` - [Version Compatibility](https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#version-compatibility)

Take your time, there is no rush if you're learning new things

**Comment by blorange2** [comment]
I submitted a pull request: https://github.com/ARCANEDEV/LogViewer/pull/302
