### ISSUE TITLE
Log Views can't install on Laravel 6.3

### ISSUE THREAD

**Issue by lakshsyal123** [ARCANEDEV/LogViewer#305]
- LogViewer Version: 4.6.0
- Laravel Version: 6.3.0
- PHP Version: 7.3.0

### Description:
https://prnt.sc/plq70x

**Comment by arcanedev-maroc** [comment]
Check this: https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#version-compatibility
