### ISSUE TITLE
Custom log levels

### ISSUE THREAD

**Issue by amacsmith** [ARCANEDEV/LogViewer#306]
I was wondering, if it would be possible and reasonable to be able to create your own log categories? Currently, I believe LogViewer is using the PSR log levels. My team has created an entry into the laravel logs for FRONTEND (javascript) errors. It would be nice if in the config you could customize the the log levels/categories. Let me know if this is something that might be interesting to implement.

**Comment by arcanedev-maroc** [comment]
You can't extend the log levels because we are following the [PSR-3](github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md) standard.

Supported levels: https://github.com/php-fig/log/blob/master/Psr/Log/LogLevel.php

**Comment by amacsmith** [comment]
Okay, that is quite alright, thanks for your timely response. I knew you were using that just didn't know if you were open for extending it. Thanks again.
