### ISSUE TITLE
3.7.0 update

### ISSUE THREAD

**Issue by days85** [ARCANEDEV/LogViewer#31]
Hello

I updated today log viewer to v3.7.0 and the following error raises every time I'm going to view log from a date:

```
ErrorException in UrlGenerator.php line 306:
Route [] not defined. (View: /var/www/html/localhost.dev/resources/views/vendor/log-viewer/_partials/menu.blade.php) (View: /var/www/html/localhost.dev/resources/views/vendor/log-viewer/_partials/menu.blade.php)
```

**Comment by arcanedev-maroc** [comment]
You need to update your `config/log-viewer.php` file.

Check this : https://github.com/ARCANEDEV/LogViewer/blob/master/config/log-viewer.php#L60
