### ISSUE TITLE
Replacing the translations with json strings for Laravel 7.x

### ISSUE THREAD

**Issue by arcanedev-maroc** [ARCANEDEV/LogViewer#311]
Docs: https://laravel.com/docs/6.x/localization#using-translation-strings-as-keys

**Comment by amacsmith** [comment]
What are the file name standards for this? Should the files be named from general.php to general.json? If so I wrote a script to convert them all and I will pr it.

**Comment by arcanedev-maroc** [comment]
I fixed your PR @amacsmith 

Thanks for your contribution

**Comment by amacsmith** [comment]
Thank you and appreciate your feed back!
