### ISSUE TITLE
with this solution can i open an external log file from log4j?

### ISSUE THREAD

**Issue by FairouzPico** [ARCANEDEV/LogViewer#315]
- LogViewer Version: 4.0
- Laravel Version: 5.2.45
- PHP Version: 5.5.12

Thank you for this solution , i want to visualize a log file from log4j it is possible with this package?is there any configuration to do ?

**Comment by arcanedev-maroc** [comment]
This package only support laravel's log files, log4j is not supported because it doesn't use PHP Monolog.
