### ISSUE TITLE
Getting error while trying to view the log details

### ISSUE THREAD

**Issue by monca13** [ARCANEDEV/LogViewer#318]
- LogViewer Version: ^5.0
- Laravel Version: 6.6.1
- PHP Version: 7.2.24

### Description:

```
join(): Passing glue string after array is deprecated. Swap the parameters (View: /home/monica/Projects/defence-new/server/resources/views/vendor/log-viewer/bootstrap-4/show.blade.php)
```

### Steps To Reproduce:
while trying to redirect to this url:
https://laravel.test/api/log-viewer/logs/2019-12-13

**Comment by arcanedev-maroc** [comment]
The bug was fixed, you need to update your views.

Check: #317

**Comment by narenderwaraich** [comment]
same problem on live server https://mynearfood.in/logs/logs/2021-09-10/error
