### ISSUE TITLE
Argument 1 passed to Arcanedev\Support\Providers\PackageServiceProvider::__construct() must be an instance of Il   luminate\Contracts\Foundation\Application, instance of Laravel\Lumen\Application given, called in /var/www/html/My-App/vendor/laravel/lumen-framework/src/Application.php on line 190

### ISSUE THREAD

**Issue by nathapawar25994** [ARCANEDEV/LogViewer#320]
- LogViewer Version: 5.1.1
- Laravel Version: 6.0
- PHP Version: 7.2

### Description:
Registered service provider in app.php
$app->register(Arcanedev\LogViewer\LogViewerServiceProvider::class);

### Steps To Reproduce:
When I execute this command above error has occurred.
php artisan log-viewer: publish

**Comment by arcanedev-maroc** [comment]
Lumen is not supported !
