### ISSUE TITLE
While Intetegrating log-viewer package getting following error

### ISSUE THREAD

**Issue by nathapawar25994** [ARCANEDEV/LogViewer#321]
- LogViewer Version: 5.1.1
- Laravel Version: 6.0
- PHP Version: 7.2

### Description:

In PackageServiceProvider.php line 65:
 Argument 1 passed to Arcanedev\Support\Providers\PackageServiceProvider::__construct() must be an instance of Illuminate\Contracts\Foundation\Application, instance of Laravel\Lumen\Application given, called in /var/www/html/My-App/vendor/laravel/lumen-framework/src/Application.php on line 190

### Steps To Reproduce:
Installed the log-viewer package via composer
Added "Arcanedev\LogViewer\LogViewerServiceProvider::class" in app.php

While executing this command
php artisan log-viewer:publish

Getting above error please help to resolve this. Thanks.

**Comment by arcanedev-maroc** [comment]
Like i've said in #320, this package support only laravel framework.

**Lumen is not Supported**
