### ISSUE TITLE
5.2.0 still fails with PHP 7.4

### ISSUE THREAD

**Issue by panique** [ARCANEDEV/LogViewer#324]
- LogViewer Version: 5.2.0
- Laravel Version: 6.12.0
- PHP Version: 7.4.2

### Description:

Showing a log under `/log-viewer/logs/2020-01-27` (example date) still gives this error:

```php
join(): Passing glue string after array is deprecated. Swap the parameters (View: /var/www/resources/views/vendor/log-viewer/bootstrap-4/show.blade.php)
```
This shouldn't happen as compatibility with PHP 7.4 was introduced in Log Viewer 5.1.7.

### Steps To Reproduce:

Thanks :)

**Comment by arcanedev-maroc** [comment]
I think you need to delete the old `resources/views/vendor/log-viewer` folder.

PR: #317

**Comment by panique** [comment]
Thanks, that's indeed the fix! :)
FYI I've spent around a day trying to fix this, maybe this info should go into the readme or even run automatically as it's a breaking change that will affect lots of people.

I'll look into this

**Comment by ToeiRei** [comment]
I deleted the folders mentioned - but the error still persists

**Comment by arcanedev-maroc** [comment]
@ToeiRei Same issue ?

`join(): Passing glue string after array is deprecated. Swap the parameters (View: /var/www/resources/views/vendor/log-viewer/bootstrap-4/show.blade.php)`

**Comment by ToeiRei** [comment]
Same error: 
```
[2020-02-03 18:24:08] Production.ERROR: join(): Passing glue string after array is deprecated. Swap the parameters (View: /home/bank/gamebank/vendor/arcanedev/log-viewer/resources/views/bootstrap-4/show.blade.php) 
```

**Comment by arcanedev-maroc** [comment]
Which versions (laravel & log-viewer) are your using ?

**Comment by ToeiRei** [comment]
Laravel 5.8 and Viewer 4.7, PHP 7.4

**Comment by arcanedev-maroc** [comment]
LogViewer v4.7 does not support PHP 7.4 (For the time being)

You can fix the issue by publishing the views and make some changes

#### bootstrap-4/show.blade.php

Replace this:
```blade
@unless (empty(log_styler()->toHighlight()))
$('.stack-content').each(function() {
    var $this = $(this);
    var html = $this.html().trim()
        .replace(/({!! join(log_styler()->toHighlight(), '|') !!})/gm, '<strong>$1</strong>');
    $this.html(html);
});
@endunless
```
With:
```blade
 @unless (empty(log_styler()->toHighlight()))
    @php
        $htmlHighlight = version_compare(PHP_VERSION, '7.4.0') >= 0
            ? join('|', log_styler()->toHighlight())
            : join(log_styler()->toHighlight(), '|');
    @endphp
    $('.stack-content').each(function() {
        var $this = $(this);
        var html = $this.html().trim()
            .replace(/({!! $htmlHighlight !!})/gm, '<strong>$1</strong>');
        $this.html(html);
    });
@endunless
```

For more details: https://github.com/ARCANEDEV/LogViewer/commit/bf69f9408ecd16bb27b409eb89aec242704dce37

**Comment by ToeiRei** [comment]
I guess I'll just see if I can get my App upgraded to Laravel 6.x

**Comment by panique** [comment]
@ToeiRei try to do all the cache resets:

```bash
cache:clear
view:clear (not sure if it's this exact command)
config:clear
```
