### ISSUE TITLE
the middleware not found

### ISSUE THREAD

**Issue by maryamMOMENII** [ARCANEDEV/LogViewer#327]
- LogViewer Version:newest
- Laravel Version: 5.8
- PHP Version: 7.2

Hi,
im using this 
but 
i set 
'middleware' => ['web','administrator'],
in config 
i give this error 
Class administrator does not exist,
how resolve this error?
when used auth, worked. and read the issues and not resolves

**Comment by arcanedev-maroc** [comment]
Because the 'administrator' is a custom middleware, you need to create it if you need this functionality.
