### ISSUE TITLE
How to add a Custom View

### ISSUE THREAD

**Issue by SupunSam** [ARCANEDEV/LogViewer#329]
- LogViewer Version: 5.2
- Laravel Version: 6.2
- PHP Version: 7.4

Description:

I am trying to change the theme of my log viewer. However, I want to use my project resources>views for this requirement. I tried to do this by using the theme option in the log-viewer.php setting. However, it seems it is looking through the vendor folder. Not in my Project Views folder.

https://flareapp.io/share/OmVDNw78?owner_token=vRQHiQfITlTFaHFwXSOUnnOa4KCS5BMQ

**Comment by arcanedev-maroc** [comment]
You can disable the LogViewer routes to use your own routes/controller/views.
