### ISSUE TITLE
View [view-name] not found.

### ISSUE THREAD

**Issue by annasindhu** [ARCANEDEV/LogViewer#331]
- LogViewer Version: 4.5
- Laravel Version: 5.6
- PHP Version: 7

### Description:
Hi i installed the application 'http://localhost/log-viewer' - showing the first page
but after clicking the 'http://localhost/log-viewer/logs' -showing ErrorException (E_ERROR)
View [view-name] not found. 

### Steps To Reproduce:

![errorname1](https://user-images.githubusercontent.com/34735237/75951824-04cee600-5ed3-11ea-86ec-e788a9e3cb6e.jpg)

**Comment by arcanedev-maroc** [comment]
I just tested the package (log-viewer v4.5) with laravel v5.6 - No issue
