### ISSUE TITLE
Log file too large error

### ISSUE THREAD

**Issue by fengerwoo** [ARCANEDEV/LogViewer#332]
- LogViewer Version: 5.2.0
- Laravel Version: 6.17.1
- PHP Version: 7.2.24

### Description:
Log file too large error

[2020-03-18 19:23:08] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 48422872 bytes) in /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:49
Stack trace:
#0 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(148): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(134): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(49): file_get_contents()
#4 /home/www/AirSDKAPI/vendor/arcanedev/log-viewer/src/Utilities/Filesystem.php(232): Illuminate\Filesystem\Filesystem->get()
#5 /home/www/AirSDKAPI/vendor/arcanedev/log-viewer/src/Entities/LogCollection.php(41): Arcanedev\LogViewer\Utilities\Filesystem->read()
#6 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Support/LazyCollection.php(99): Arcanedev\LogViewer\Entities\LogCollection->Arcanedev\LogViewer\Entities\{closure}()
#7 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Support/LazyCollection.php(99): iterator_to_array()
#8 /home/www/AirSDKAPI/vendor/arcanedev/log-viewer/src/Entities/LogCollection.php(148): Arcanedev\LogViewer\Entities\LogCollection->all()
#9 /home/www/AirSDKAPI/vendor/arcanedev/log-viewer/src/Utilities/Factory.php(231): Arcanedev\LogViewer\Entities\LogCollection->stats()
#10 /home/www/AirSDKAPI/vendor/arcanedev/log-viewer/src/Utilities/Factory.php(243): Arcanedev\LogViewer\Utilities\Factory->stats()
#11 /home/www/AirSDKAPI/vendor/arcanedev/log-viewer/src/LogViewer.php(237): Arcanedev\LogViewer\Utilities\Factory->statsTable()
#12 /home/www/AirSDKAPI/vendor/arcanedev/log-viewer/src/Http/Controllers/LogViewerController.php(69): Arcanedev\LogViewer\LogViewer->statsTable()
#13 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Arcanedev\LogViewer\Http\Controllers\LogViewerController->index()
#14 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array:{/home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54}()
#15 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Arcanedev\LogViewer\Http\Controllers\LogViewerController->callAction()
#16 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch()
#17 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#18 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#19 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}()
#21 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Routing\Pipeline->then()
#22 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack()
#23 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute()
#24 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute()
#25 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch()
#26 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): App\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#27 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}()
#28 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#29 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}()
#30 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\TrimStrings->handle()
#31 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}()
#32 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#33 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}()
#34 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForMaintenanceMode->handle()
#35 /home/www/AirSDKAPI/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}()
#36 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\TrustProxies->handle()
#37 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}()
#38 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Routing\Pipeline->then()
#39 /home/www/AirSDKAPI/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): App\Http\Kernel->sendRequestThroughRouter()
#40 /home/www/AirSDKAPI/public/index.php(55): App\Http\Kernel->handle()
#41 /home/www/AirSDKAPI/public/index.php(0): {main}()
#42 {main}

**Comment by arcanedev-maroc** [comment]
Duplicate: #21
