### ISSUE TITLE
hey, can anyone tell me why i cant change log files pattern in logviewer config? when i tried to change prefix, all of the logs had gone looks like it can only be 'laravel-'. am i right or there is a solution for it

### ISSUE THREAD

**Issue by aryala7** [ARCANEDEV/LogViewer#333]
- LogViewer Version: latest
- Laravel Version: 5.8
- PHP Version: 7.1.3

### Steps To Reproduce:
go to the log-viewer.php and  change  Filesystem::PATTERN_PREFIX  to whatever you want

**Comment by arcanedev-maroc** [comment]
What your logs files looks like ?

Check #135 for more details

**Comment by MichaelCorrea478** [comment]
I am with the same issue. I need LogViewer to match these patterns: order-2022-03-25.log, product-2022-03-25.log, customer-2022-03-25.log and laravel-2022-03-25.log.
I tried to change the PATTERN_PREFIX constant in the Filesystem interface to this: const PATTERN_PREFIX    = '(laravel-|product-|customer-|order-)';
But it does not work. It does not raise any error, but seems that it does not match any of my log files.
