### ISSUE TITLE
I am getting following error while installing package

### ISSUE THREAD

**Issue by jigarhalani** [ARCANEDEV/LogViewer#334]
- LogViewer Version: ~4.6.0
- Laravel Version: 5.8
- PHP Version: 7.2

### Description:

 Problem 1
    - Installation request for arcanedev/support (locked at 4.5.0) -> satisfiable by arcanedev/support[4.5.0].
    - arcanedev/log-viewer 4.6.0 requires arcanedev/support ~4.4.0 -> satisfiable by arcanedev/support[4.4.0].
    - arcanedev/log-viewer 4.6.1 requires arcanedev/support ~4.4.0 -> satisfiable by arcanedev/support[4.4.0].
    - arcanedev/log-viewer 4.6.2 requires arcanedev/support ~4.4.0 -> satisfiable by arcanedev/support[4.4.0].
    - arcanedev/log-viewer 4.6.3 requires arcanedev/support ~4.4.0 -> satisfiable by arcanedev/support[4.4.0].
    - arcanedev/log-viewer 4.6.4 requires arcanedev/support ~4.4.0 -> satisfiable by arcanedev/support[4.4.0].
    - arcanedev/log-viewer v4.6.x-dev requires arcanedev/support ~4.4.0 -> satisfiable by arcanedev/support[4.4.0].
    - Conclusion: don't install arcanedev/support 4.4.0
    - Installation request for arcanedev/log-viewer ~4.6.0 -> satisfiable by arcanedev/log-viewer[4.6.0, 4.6.1, 4.6.2, 4.6.3, 4.6.4, v4.6.x-dev].

### Steps To Reproduce:
composer require arcanedev/log-viewer:~4.6.0

**Comment by arcanedev-maroc** [comment]
Wrong version: https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#version-compatibility
