### ISSUE TITLE
Patch released: `v4.6.1`

### ISSUE THREAD

**Issue by Zain541** [ARCANEDEV/LogViewer#336]
Patch released: `v4.6.1`

_Originally posted by @arcanedev-maroc in https://github.com/ARCANEDEV/LogViewer/issues/234#issuecomment-430158930_

How to fix this in laravel 5.5 since laravel 5.5 supports 4.4.x version?

**Comment by arcanedev-maroc** [comment]
The LogViewer v4.4 does not support PHP 7.3

Try to upgrade the whole project (Laravel + LogViewer) instead
