### ISSUE TITLE
Suggestion to have a helper function to get a number of logs.

### ISSUE THREAD

**Issue by 77media-creations** [ARCANEDEV/LogViewer#337]
- LogViewer Version: 7.0
- Laravel Version: 7.x
- PHP Version: 7.4.0

### Description:
I like this package. 
Was just wondering if a helper function can be made to check the number of logs in a particular group/level. 
It may be helpful to show this number in a header or sidebar as a badge, giving you a hint about the number of logs.

For Example:
`no_of_logs('error')`
`// 10`

`no_of_logs('info')`
`// 5`

**Comment by arcanedev-maroc** [comment]
No plan for this feature
