### ISSUE TITLE
join(): Passing glue string after array is deprecated.

### ISSUE THREAD

**Issue by jigarhalani** [ARCANEDEV/LogViewer#338]
- LogViewer Version: ~4.7.0
- Laravel Version: 5.8
- PHP Version: 7.2

### Description:
getting below error after updating the package.

![image](https://user-images.githubusercontent.com/15965253/81173967-8f5cc000-8fbe-11ea-9038-67d43ff7e8f1.png)

### Steps To Reproduce:
- install package and open any log file

**Comment by NovaDust69** [comment]
Hi,
As you see it's hardcoded in the blade.
expose in your \views structure the template by copying it
from \vendor\arcanedev\log-viewer\resources\views\bootstrap-4
to /views/log-viewer/bootstrap-4

You can after switch in the file \resources\views\vendor\log-viewer\bootstrap-4\show.blade.php the argument of the join function ;
join( log_styler()->toHighlight(),'|' ) -> join('|', log_styler()->toHighlight() )

Happy coding!
