### ISSUE TITLE
Multiline logs support

### ISSUE THREAD

**Issue by raveren** [ARCANEDEV/LogViewer#339]
I can't believe I'm the first one to be bothered by this, but the logviewer does not display multiline log entries properly:

```

[2020-05-15 11:56:19] local.DEBUG: array (
  'dirname' => '.',
  'basename' => 'redacted',
  'extension' => 'pdf',
  'filename' => 'redacted',
)  
[2020-05-15 11:58:24] local.ERROR: redacted
```

![image](https://user-images.githubusercontent.com/364220/82033389-551dad80-96a5-11ea-8e40-3ecb051293be.png)

**Comment by arcanedev-maroc** [comment]
Feel free to make a PR

**Comment by raveren** [comment]
sorry guy, but how is anyone starring or using this crap is beyond me
