### ISSUE TITLE
View [mytheme.dashboard] not found

### ISSUE THREAD

**Issue by ArabAgile** [ARCANEDEV/LogViewer#340]
- LogViewer Version: 5.2.0
- Laravel Version: 6.18.6
- PHP Version: 7.2.11

### Description:
LogViewer is not compatible with my theme. I am getting this error when installing it:
```
View [mytheme.dashboard] not found
```

I had my own theme, and it has complicated structure and hierarchies. How to make LogViewer working with my own theme?

### Steps To Reproduce:

I can find `theme` config, but when changing the value to my theme `mytheme` it is showing the above error. My theme structure don't have `dashboard` file as it has it's unique structure.

**Comment by arcanedev-maroc** [comment]
The templating doesn't work like.

If you want to create a new custom template (`mytheme` for example) you must have three files: 

 * `mytheme/dashboard.blade.php`
 * `mytheme/logs.blade.php`
 * `mytheme/show.blade.php`
