### ISSUE TITLE
Arcanedev\LogViewer\Commands\PublishCommand

### ISSUE THREAD

**Issue by DejvIT** [ARCANEDEV/LogViewer#343]
- LogViewer Version: 7.0
- Laravel Version: 7.13.0
- PHP Version: 7.2.5

### Description:
Trying to install package, but when I do the step number 2. registering the provider the error occurs for every php artisan command like cache:clear, config:clear... or publish vendor etc..
Here is the image of error output.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/35288070/83420715-4c5c0400-a427-11ea-881a-12c1a72144a6.png">

**Comment by arcanedev-maroc** [comment]
The step 2 is only for Laravel v5.4 or lower. You can skip it!
