### ISSUE TITLE
LogViewer middleware destroying sessions

### ISSUE THREAD

**Issue by rsoares88** [ARCANEDEV/LogViewer#344]
- LogViewer Version: ~7.0
- Laravel Version: ^7.0
- PHP Version: ^7.2.5

### Description:
Im using custom data in session for a middleware, but LogViewer is not passing it for some reason.

Doing $request->session() in middleware will give error:

```
RuntimeException
Session store not set on request.
```

### Steps To Reproduce:
Try to access sessions in middleware

**Comment by rsoares88** [comment]
It randomly started to work LOL

**Comment by arcanedev-maroc** [comment]
Check this issue: #69
