### ISSUE TITLE
 expanding the record body hides the context switch

### ISSUE THREAD

**Issue by abdelaziz321** [ARCANEDEV/LogViewer#349]
- LogViewer Version: 7.x
- Laravel Version: 7.2.5
- PHP Version: 7.2.24

### Description:
If we want to expand the log entry, we hit the `context switch`
![Screenshot from 2020-07-01 06-07-04](https://user-images.githubusercontent.com/21992961/86202109-a86a9300-bb61-11ea-897b-e24f7e0d67fd.png)

But If the body was a long string, the `context switch` will be hidden at the end of the record row.
![Screenshot from 2020-07-01 06-08-21](https://user-images.githubusercontent.com/21992961/86202234-fda6a480-bb61-11ea-994b-ccc291bfb833.png)

The expected behavior is to wrap the string, so we can see something like that
![Screenshot from 2020-07-01 06-10-07](https://user-images.githubusercontent.com/21992961/86202303-26c73500-bb62-11ea-93a2-4d0e67230fd3.png)

**Comment by arcanedev-maroc** [comment]
Why the value of `response` in the context is not an array ?

Example:

```php
info('api/family/user', [
    'method'  => 'GET',
    'request' => [],
    'response' => [
        'user' => [
            'id'         => 1,
            'first_name' => 'John',
            'last_name'  => 'DOE',
        ],
    ],
]);
```

![2020-07-06_09-50-41](https://user-images.githubusercontent.com/3282340/86574866-603ade80-bf6e-11ea-9769-d606e6073199.jpg)

I'm closing this issue because it works fine for me. Otherwise, you can publish/edit the views in your project.

**Comment by abdelaziz321** [comment]
mmm...
ok, thanks for the example :)
