### ISSUE TITLE
Target [Arcanedev\LogViewer\Contracts\LogViewer] is not instantiable while building [Arcanedev\LogViewer\Http\Controllers\LogViewerController]. 

### ISSUE THREAD

**Issue by MiquelRoan** [ARCANEDEV/LogViewer#352]
- LogViewer Version: 5.2.0
- Laravel Version: 6.18.23
- PHP Version: 7.3.19

### Description: I can't get into the log view. I get error:
`Illuminate\Contracts\Container\BindingResolutionException
Target [Arcanedev\LogViewer\Contracts\LogViewer] is not instantiable while building [Arcanedev\LogViewer\Http\Controllers\LogViewerController]. `

**Comment by huiyang** [comment]
@MiquelRoan did you solve this issue? I have the same issue installing arcanedev/log-viewer 5.2.0 at laravel/framework v6.20.16

**Comment by huiyang** [comment]
I solved the issue after remove `arcanedev/log-viewer` from the don't discover list in composer.json. Thanks anyway!
