### ISSUE TITLE
Hello. In future versions you will be able to download a log based on a search query?

### ISSUE THREAD

**Issue by SEFkiss** [ARCANEDEV/LogViewer#355]
- LogViewer Version: 7.0.0
- Laravel Version: 7.19.0
- PHP Version: 7.3.9

### Description:
Hello. In future versions you will be able to download a log based on a search query?

**Comment by arcanedev-maroc** [comment]
Hi @SEFkiss,

I can't promise you this will be in future releases but if you want to add it in your project. 

Try to override the default routes/controller/views.

Check #83 for more details
