### ISSUE TITLE
How to download logs in csv format ?

### ISSUE THREAD

**Issue by rishab0** [ARCANEDEV/LogViewer#356]
- LogViewer Version: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#

### Description:

i want to download logs in csv format

**Comment by arcanedev-maroc** [comment]
I can't add this feature (and i don't recommend it). 

But you can add it in your own project by overriding the default routes/views/controller.

**Comment by rishab0** [comment]
Hi, Thanks for reply, 
yes, i do customised download function in vendor folder. 
But when i do 'composer update'. my code is set to default. :(

**Comment by arcanedev-maroc** [comment]
Check this: https://github.com/ARCANEDEV/LogViewer/issues/83#issuecomment-249430860

**Comment by rishab0** [comment]
Hello, 
please help me 
how i publish package?
sorry, but i did not find PackagesServiceProvider.php or other files mentioned in points.
