### ISSUE TITLE
PHP 7.4 View Log 500 Error

### ISSUE THREAD

**Issue by adisnabawi** [ARCANEDEV/LogViewer#357]
- LogViewer Version: 7.0
- Laravel Version: 7.0
- PHP Version: 7.4

### Description:
500 Error view file
join(): Passing glue string after array is deprecated. Swap the parameters (View: /www/adis/vendor/arcanedev/log-viewer/views/bootstrap-4/show.blade.php){"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): join(): Passing glue string after array is deprecated. Swap the parameters (View: /www/adis/vendor/arcanedev/log-viewer/views/bootstrap-4/show.blade.php) at /www/adis/vendor/arcanedev/log-viewer/views/bootstrap-4/show.blade.php:267)

### Steps To Reproduce:
Clicking at the view icon
![image](https://user-images.githubusercontent.com/11766368/88160926-ea0ecb00-cc41-11ea-96aa-e96c9aa81337.png)

**Comment by arcanedev-maroc** [comment]
I can't reproduce your issue. It's working fine for me!

Laravel version: 7.21.0
LogViewer version: 7.0.0
PHP version: 7.4.0

PR: #317

**Comment by adisnabawi** [comment]
I still get the error.  I tried in my local 7.3 no issues. Only 7.4 has issues. I check the suggestion and I saw the file is up to date. Is it because I'm using 7.4.0RC4?

**Comment by adisnabawi** [comment]
The issues is with this version_compare(PHP_VERSION, '7.4.0'). I upgrade my php version to 7.4.8 and now it's OK.
