### ISSUE TITLE
Can not open views

### ISSUE THREAD

**Issue by narkoze** [ARCANEDEV/LogViewer#360]
- LogViewer Version: 7.0.0
- Laravel Version: 7.0.8
- PHP Version: 7.2.32

### Description:
Can not open views

`htmlspecialchars() expects parameter 1 to be string, array given (View: /Users/ev/p/aep/resources/views/vendor/log-viewer/bootstrap-4/dashboard.blade.php)`

`htmlspecialchars() expects parameter 1 to be string, array given (View: /Users/ev/p/aep/resources/views/vendor/log-viewer/bootstrap-4/logs.blade.php)`

`<span class="box-text">{{ $item['name'] }}</span>`

`"info" => array:3 [▼
    "name" => array:1 [▼
      "project" => array:1 [▼
        "title" => "Project"
      ]
    ]`

**Comment by arcanedev-maroc** [comment]
Can you explain how to reproduce it in fresh laravel application ?

**Comment by narkoze** [comment]
It is because i have my translate at resources/lang/en/info.php :)
