### ISSUE TITLE
Unused variables passed into the show.blade.php

### ISSUE THREAD

**Issue by egorsmkv** [ARCANEDEV/LogViewer#362]
- LogViewer Version: 7.0.0
- Laravel Version:  7.27.0
- PHP Version: 7.4.8

### Description:

I am using laravel-microsope and it detected an issue where https://github.com/ARCANEDEV/LogViewer/blob/master/src/Http/Controllers/LogViewerController.php#L128 is not used in the 
show.blade.php file and I am seeing it in the logs.

![image](https://user-images.githubusercontent.com/7875085/91899268-91513a00-eca5-11ea-89db-07a0b2cd736c.png)

### Steps To Reproduce:

Just install the library.

**Comment by arcanedev-maroc** [comment]
The variable is available for users who customize the `views`

Also, this is not a bug. Even in the log it's displayed as an `info`
