### ISSUE TITLE
[Feature] Filtering by 'priority up'

### ISSUE THREAD

**Issue by spekulatius** [ARCANEDEV/LogViewer#365]
Hey @arcanedev-maroc 

I'm using the LogViewer (v7.1) as Nova package using [Nova Logs](https://github.com/PHPJunior/nova-logs). I was wondering if you considered this feature: 

I generally organize my logging to cover priority up (more critical things get higher priority). I think that's super logical and most people follow this approach naturally. I feel it would be great to see it this way too. Meaning, if selecting "Alert" I would like to see both "Alert" and "Emergency", if selecting "Critical" I would like to see "Critical", "Alert" and "Emergency". This would enable debugging issues better while going down the priorities.

I would love to hear what you are thinking.

Cheers,
Peter

**Comment by arcanedev-maroc** [comment]
I'm not big fan of this feature because it will confuse a lot of the users

If i select the lowest log level (debug) for example, it will show me all the log entries.

**Comment by spekulatius** [comment]
Okay, fair enough. It was simply a thought 👍️

**Comment by arcanedev-maroc** [comment]
What i can suggest is adding a multi-levels filter, so you can select only the levels you're interested in.

**Comment by spekulatius** [comment]
Ah okay, so you would select one or more levels and get these as a combined view? That sounds like a good middle way.
