### ISSUE TITLE
RouteServiceProvider error on running update

### ISSUE THREAD

**Issue by claytical** [ARCANEDEV/LogViewer#37]
I just ran an update through composer and it failed with the following message:

Declaration of Arcanedev\LogViewer\Providers\RouteServiceProvider::map() must be compatible with Arcanedev\Support\Providers\RouteServiceProvider::map(Illuminate\Contracts\Routing\Registrar $router) 

BTW I'm using the LogViewer through @RappaSoft's boilerplate if that's any help.

**Comment by arcanedev-maroc** [comment]
Hi @claytical, sorry about that.

I've made some changes to make sure that the `RouteServiceProvider` use an abstract Router instance of a concrete class. 

Try to update your dependencies by running `composer update --no-scripts`

**Comment by nasirkhan** [comment]
@arcanedev-maroc could you please update and mention the doc so that i can resolve this issue. Doi need to use `composer update --no-scripts` each time i update composer? should i use the version 3.0 instead of 3.7?

**Comment by razan-rai** [comment]
yes worked with "composer update --no-scripts" thanx.
