### ISSUE TITLE
https://code.jquery.com/jquery-3.2.1.min.js 此站点以关闭，可以换一个吗

### ISSUE THREAD

**Issue by fujinghua** [ARCANEDEV/LogViewer#374]
- LogViewer Version: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#

### Description:
https://code.jquery.com/jquery-3.2.1.min.js 此站点以关闭，可以换一个吗

### Steps To Reproduce:
https://code.jquery.com/jquery-3.2.1.min.js 换成
http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.1.min.js

**Comment by arcanedev-maroc** [comment]
Hi @fujinghua. Sorry, i can't understand your language.

But after using a translator: `This site is closed, can we get another one?`. 

You can switch jquery by publishing/editing the views in your project: `php artisan log-viewer:publish`

The jquery still working for me, i think is blocked in your country
