### ISSUE TITLE
Delete/Hide individual log items

### ISSUE THREAD

**Issue by mo523** [ARCANEDEV/LogViewer#376]
- LogViewer Version: 7.0.0
- Laravel Version: 7.0
- PHP Version: 5.7.24

### Description:

Is there a way to delete individual log items from a daily log file? Or mark them as hidden and have an option to show hidden if you don't want to delete them.

If not I would be happy to work on it.
The log viewer already has the 'action' button, so another button ('hide') would probably go with the look.

**Comment by arcanedev-maroc** [comment]
This feature is not available because the log entries are not stored as database entries. 

So you can't delete individual entries or mark then as hidden.

But feel free to create a PR. Just make just is not a breaking change :+1:
