### ISSUE TITLE
Pagination visual is broken

### ISSUE THREAD

**Issue by SergioGMB** [ARCANEDEV/LogViewer#377]
- LogViewer Version: 8.0.2
- Laravel Version: 8.18.1
- PHP Version: 7.4.9

### Description:

<img width="1143" alt="Captura de pantalla 2020-12-11 a las 11 17 30" src="https://user-images.githubusercontent.com/66242403/101891564-82cac680-3ba2-11eb-9571-802c02584ea3.png">

### Steps To Reproduce:
Just logging more than 30 logs, makes the pagination appear and it's broken.

NOTE: I also noticed the version displaying in the footer is still 8.0.1, but i have 8.0.2 installed

**Comment by arcanedev-maroc** [comment]
This package doesn't have a tailwindcss template as default.

Check the official documentation: https://laravel.com/docs/8.x/upgrade#pagination

I'll add a note about this and fixing also the version.

Thanks :+1:
