### ISSUE TITLE
join(): Passing glue string after array is deprecated

### ISSUE THREAD

**Issue by juliv** [ARCANEDEV/LogViewer#379]
- LogViewer Version: 4.4.5
- Laravel Version: 5.5.50
- PHP Version: 7.4.13

### Description:
join(): Passing glue string after array is deprecated.
Swap the parameters (View: `\resources\views\vendor\log-viewer\show.blade.php`)

### Steps To Reproduce:
View any log file.
Example: /log-viewer/logs/2021-01-03

**Comment by arcanedev-maroc** [comment]
Check this comment: https://github.com/ARCANEDEV/LogViewer/issues/324#issuecomment-581535976
