### ISSUE TITLE
Fatal error after composer update

### ISSUE THREAD

**Issue by rappasoft** [ARCANEDEV/LogViewer#38]
Not sure if this is just my specific installation, but I did a composer update from arcanedev/support 3.6.10 to 3.7.1 and I now have the following error stopping my entire application from running:

```
Error Output: PHP Fatal error:  Declaration of Arcanedev\LogViewer\Providers\RouteS
  erviceProvider::map() must be compatible with Arcanedev\Support\Providers\RouteServ
  iceProvider::map(Illuminate\Contracts\Routing\Registrar $router) in /home/vagrant/C
  ode/GitHub/Larave5LargeScaleBP/vendor/arcanedev/log-viewer/src/Providers/RouteServi
  ceProvider.php on line 15
```

Any ideas?

**Comment by rappasoft** [comment]
Disregard. Changed composer from ~3.5.0 to ~3.0 and it works now.

**Comment by arcanedev-maroc** [comment]
Check this: #37

**Comment by rappasoft** [comment]
Interesting, I have it all working except the show page. It seems ```$log->menu()``` is throwing a ```Route [] not defined.``` not defined. I can't figure out why.

**Comment by arcanedev-maroc** [comment]
You need also to check this #31.

**Comment by rappasoft** [comment]
Perfect thank you.
