### ISSUE TITLE
limit total amount of files

### ISSUE THREAD

**Issue by jopsilva** [ARCANEDEV/LogViewer#383]
- LogViewer Version: "arcanedev/log-viewer": "~5"
- Laravel Version: "laravel/framework": "^6.0",
- PHP Version:7.3

### Description:
can I limit the amount of files that will be shown on the dashboard?

**Comment by arcanedev-maroc** [comment]
You question is very vague, but you can limit the log files by changing the 'days' value:

```php
'daily' => [
    'driver' => 'daily',
    'path' => storage_path('logs/laravel.log'),
    'level' => env('LOG_LEVEL', 'debug'),
    'days' => 14, // <----
],
```
