### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by sakinobashi** [ARCANEDEV/LogViewer#384]
I use LogViewer on all of my projects, and I was interested in making sort of a "LogViewer summary page" where the summary for the last 'n' days of each domain would be displayed (like the /log-viewer/logs page, only limited to 'n' days and showing multiple domains).

I can see that an API exists, but there's no documentation and I don't even know if it would work for my use case. Is there any chance of getting some documentation, even something brief, so that people like me had at least a starting point? I'm hardly a good enough developer to do it myself, to be honest. Even a simple pointer to the classes we should use and/or a simple code example would be most helpful.

**Comment by arcanedev-maroc** [comment]
Hi @sakinobashi, thanks for using this package!

It is a complicated task to create and maintain a perfect API doc that covers all the source code.

But what i recommend is consulting the [Contracts Folder](https://github.com/ARCANEDEV/LogViewer/tree/master/src/Contracts), they are minimal and it contains all the main/public methods without getting lost in the source code.

And you can use these contracts directly as a type-hinted dependency. You can also check the `tests` folder to learn about the usage.

If you had any questions/issues, i'll do my best to assist you.

Also feel free to make a PR to improve the documentation and helping other users :+1:
