### ISSUE TITLE
Target [Arcanedev\LogViewer\Contracts\LogViewer] is not instantiable while building [Arcanedev\LogViewer\Http\Controllers\LogViewerController].

### ISSUE THREAD

**Issue by RootAndroid58** [ARCANEDEV/LogViewer#385]
- LogViewer Version: ^8.1
- Laravel Version: 8.40.0
- PHP Version: PHP 8.0 (ea-php80)

### Description:
https://flareapp.io/share/x7XB1AVm#F45

idk its was working fine in local env but when i uploaded the code to shared hosting its giving this error

i tried to set the routes https://github.com/ARCANEDEV/LogViewer/issues/6#issuecomment-139063495 from this comment but nothing changed 

### Steps To Reproduce:

nothing followed the install process and it workes on local env but when i upload to shared hosting it giving this error

**Comment by arcanedev-maroc** [comment]
Check #323
