### ISSUE TITLE
Why myproject/log-viewer shows empty logs page?

### ISSUE THREAD

**Issue by sergeynilov** [ARCANEDEV/LogViewer#386]
Hello,
I want to add ARCANEDEV/LogViewer plugin to my laravel 8 app

but opening  http://myproject/log-viewer/logs I see that list of logs is, 
meanwhile file /storage/logs/laravel.log of my project os not empty.
Why so and why my log file is entitled as "laravel.log" without days when
log was filled? Not sure that I changed some config options. 
How it can be checked/fixed?

```
        "arcanedev/log-viewer": "^8.1",
        "laravel/framework": "^8.12",
```

Thanks!

**Comment by arcanedev-maroc** [comment]
Check the [documentation](https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#application-requirements)
