### ISSUE TITLE
How tochange css style if needed

### ISSUE THREAD

**Issue by theankitjais** [ARCANEDEV/LogViewer#388]
I tried changing css in /vendor/arcanedev/log-viewer/resources/views/bootstrap-4/ but it did not get reflected. Help

**Comment by theankitjais** [comment]
> I tried changing css in /vendor/arcanedev/log-viewer/resources/views/bootstrap-4/ but it did not get reflected. Help

I want to put a style 

```
.table td, .table th {
    overflow-wrap: anywhere !important;
}
```

**Comment by arcanedev-maroc** [comment]
Check the [answered issues](https://github.com/ARCANEDEV/LogViewer/issues?q=is%3Aissue+is%3Aclosed+label%3Acustomization)
