### ISSUE TITLE
big svg paginators

### ISSUE THREAD

**Issue by ptofladif** [ARCANEDEV/LogViewer#389]
- LogViewer Version: 8.1
- Laravel Version: 8
- PHP Version: 8

### Description:
big paginators "<" and ">"

<path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"></path>

### Steps To Reproduce:

when viewing any day list of logs

is there a way to define max size of those svg paginators buttons??

thanks

**Comment by ptofladif** [comment]
![image](https://user-images.githubusercontent.com/10712577/122582353-f963e780-d04f-11eb-8747-e9622ff1cfb9.png)

**Comment by arcanedev-maroc** [comment]
Check #377
