### ISSUE TITLE
Not working in Laravel 8

### ISSUE THREAD

**Issue by nasreddinedev1** [ARCANEDEV/LogViewer#390]
- LogViewer Version: 8.1
- Laravel Version: 8.0
- PHP Version: 7.3

### Description:
when I execute : php artisan log-viewer:check,  I see that is configured correctly,
when I access to the page, no result, empty list !!!

### Steps To Reproduce:
Just install it in Laravel 8 and you will see ncha allah the same problem with me

**Comment by arcanedev-maroc** [comment]
Do you have log files in your project? 

Check the `storage/logs` folder is not empty and it contains daily log files

**Comment by cwilby** [comment]
Picking this up where @nasreddinedev1 left off.  

LogViewer Version: 8.1
Laravel Version: 8.49.2
PHP Version: 8.0.8

Same description and reproduction steps.  `php artisan log-viewer:check` reports success, but when I access the page there are no log entries.

* I do see log files in `storage/logs`
* Vanilla config
* All log channels are daily

**Comment by fbollon** [comment]
same for me i use log-viewer in several laravel projects under different versions without problems, but here in a new project from scratch with sail as development environment no result, the list of logs is empty while i have a log file in storage/logs

**Comment by FullMe7alJacke7** [comment]
Happening to me as well... Anyone ever found a way to resolve this?
