### ISSUE TITLE
Memory Size exceeded

### ISSUE THREAD

**Issue by zisan34** [ARCANEDEV/LogViewer#393]
- LogViewer Version: 8.0.0
- Laravel Version: 8.12
- PHP Version: 7.4

### Description:
I've never created an issue before. So please forgive my mistakes. So my app is in Staging and I'm getting this exception that **"Allowed memory size of 134217728 bytes exhausted (tried to allocate 49590464 bytes)"** I know some people might say make the memory limit to -1 from .ini file. But that's an evil approach. So I believe the files got very larger & this package is trying to load the whole files in the memory that's might be the reason for the memory limit exceeding. So I think if you stream read the file, or read & load it chunk by chunk then it could solve the problem. Also using generator functions of PHP could reduce memory usage.

### Steps To Reproduce:
I had 3 days log. The main Laravel.log file was 148MB.
You can see these screenshots for better reference: [https://prnt.sc/1bcnkmi](url) ,  [https://prnt.sc/1bcrxbl](url) 

Finally, Thanks for your time & consideration.

**Comment by arcanedev-maroc** [comment]
Check this: https://github.com/ARCANEDEV/LogViewer/issues/21#issuecomment-151564025
