### ISSUE TITLE
htmlspecialchars error, translation strings mix up

### ISSUE THREAD

**Issue by ZBrettonYe** [ARCANEDEV/LogViewer#396]
- LogViewer Version: 7.1.0
- Laravel Version: 7.30.4
- PHP Version: 7.3.28

### Description:

Error message：htmlspecialchars() expects parameter 1 to be string, array given

it happened at bootstrap-4/dashboard.blade.php:23
"{{ $item['name'] }}"
![image](https://user-images.githubusercontent.com/18015854/132126776-7d1450fa-9f78-4f1d-9c55-7ef22778c846.png)

It looks like the translation string is mix up with my project's translation string.

### Steps To Reproduce:
1. create a **error.php** translation file under resources/lang/en
2. file contains 
```php
<?php

return [1,2,3,4];
```
3. view the page http://localhost/log-viewer

**Comment by arcanedev-maroc** [comment]
I think the only way to solve this issue is to rename the `error.php` file into something else like `errors.php`

Or by using [Translation Strings As Keys](https://laravel.com/docs/8.x/localization#using-translation-strings-as-keys) instead
