### ISSUE TITLE
FatalErrorException in RouteServiceProvider.php line 15:

### ISSUE THREAD

**Issue by encodia** [ARCANEDEV/LogViewer#40]
Hi, running composer update this morning, I am getting this fatal error.

[RuntimeException]                                                                                                                                                                       
Error Output: PHP Fatal error:  Declaration of Arcanedev\LogViewer\Providers\RouteServiceProvider::map() must be compatible with Arcanedev\Support\Providers\RouteServiceProvider::map(I 
lluminate\Contracts\Routing\Registrar $router) in /home/vagrant/Code/www/vendor/arcanedev/log-viewer/src/Providers/RouteServiceProvider.php on line 15                                                                                                                                                                                    

Anyone could help?

Thank you

**Comment by ChristianGiupponi** [comment]
Same error after `composer update`

**Comment by antennaio** [comment]
Getting the same error on `composer install` or `composer update`.

**Comment by arcanedev-maroc** [comment]
Check this issue: #37

**Comment by ChristianGiupponi** [comment]
It doesnt solve the issue, works for the update but as soon as I visit the site I get:

~~~
FatalErrorException in RouteServiceProvider.php line 15:
Declaration of Arcanedev\LogViewer\Providers\RouteServiceProvider::map() must be compatible with Arcanedev\Support\Providers\RouteServiceProvider::map(Illuminate\Contracts\Routing\Registrar $router)
~~~

**Comment by encodia** [comment]
Hi @arcanedev-maroc,
we did `composer update --no-script`, but we are getting the same wrong result.

**Comment by arcanedev-maroc** [comment]
Upgrade the log-viewer package to the latest version (See #41).
