### ISSUE TITLE
JSON Support

### ISSUE THREAD

**Issue by armageddan** [ARCANEDEV/LogViewer#404]
Since there is no usage documentation yet, is there support for JSON API Endpoint? So we can get a response of JSON and maybe create a custom view within an SPA

**Comment by arcanedev-maroc** [comment]
You need to create a custom Controller/routes for your JSON API.

The LogViewer's entities (like LogEntry, LogEntryCollection ...) are JSON friendly because they're implementing the `Illuminate\Contracts\Support\Jsonable` Contract.
