### ISSUE TITLE
arcanedev logviewer pagination icon twice

### ISSUE THREAD

**Issue by ahadtaji21** [ARCANEDEV/LogViewer#416]
arcanedev logviewer pagination icon twice

Laravel 8
PHP 7.4
bootstrap 4

it is showing twice pagination ico
![error](https://user-images.githubusercontent.com/48250356/168538060-865489b9-b337-49b6-b279-55ca3d34a86e.JPG)
n

**Comment by isudakoff** [comment]
Same issue

Laravel 8
PHP 8.1.3
Bootstrap 4

![logs_screenshot2](https://user-images.githubusercontent.com/2142861/170249311-2e2baa4e-8245-4a3c-920e-157c3d2922c6.png)

**Comment by ahadtaji21** [comment]
yes, I research a lot and I think we need to stop the tailwind CSS disabled. Maybe. 
hope so administrator could share a solution

**Comment by isudakoff** [comment]
Yeah! I reread docs again and fix it.

- **Important Note** in package docs: https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#important-note
- Laravel Docs: https://laravel.com/docs/8.x/upgrade#pagination-defaults

Now it looks perfect!
<img width="1680" alt="Снимок экрана 2022-05-25 в 14 28 49" src="https://user-images.githubusercontent.com/2142861/170252007-1b59d405-f71d-4770-88d5-0d87064601c0.png">

**Comment by ahadtaji21** [comment]
could you tell what actually changes you have done

**Comment by ahadtaji21** [comment]
> Yeah! I reread docs again and fix it.
> 
> * **Important Note** in package docs: https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#important-note
> * Laravel Docs: https://laravel.com/docs/8.x/upgrade#pagination-defaults
> 
> Now it looks perfect! <img alt="Снимок экрана 2022-05-25 в 14 28 49" width="1680" src="https://user-images.githubusercontent.com/2142861/170252007-1b59d405-f71d-4770-88d5-0d87064601c0.png">

could you let me the changes as I'm facing error. I have change in "App Service provider" file

**Comment by ahadtaji21** [comment]
I'm facing this error

Undefined property: Illuminate\Pagination\LengthAwarePaginator::$render (View: C:\xampp\htdocs\screening\resources\views\vendor\log-viewer\bootstrap-4\show.blade.php)

**Comment by ahadtaji21** [comment]
I also done it creating a simple mistake.

@if ($entries->hasPages())
                    <div class="panel-footer">
                        {!! $entries->appends(compact('query'))->render() !!}

                        <span class="label label-info pull-right">
                            @lang('Page :current of :last', ['current' => $entries->currentPage(), 'last' => $entries->lastPage()])
                        </span>
                    </div>
                @endif

replace your pagination render code.

**Comment by yi4396** [comment]
The paginator now uses the [Tailwind CSS framework](https://tailwindcss.com/) for its default styling. In order to keep using Bootstrap, you should add the following method call to the boot method of your application's AppServiceProvider:

use Illuminate\Pagination\Paginator;
 
Paginator::useBootstrap();
