### ISSUE TITLE
Got Error When Use role custom middleware 

### ISSUE THREAD

**Issue by ebeliejinfren** [ARCANEDEV/LogViewer#419]
- LogViewer Version: 9.0.0
- Laravel Version: 9.0.0
- PHP Version: 8

### Description:
Hi
according docs when add my custom middleware it got error
My Config in **env** :
`ARCANEDEV_LOGVIEWER_MIDDLEWARE=role:admin`

My **Middleware**:
```
public function handle(Request $request, Closure $next , string $role)
    {
        if ($request->user()->roles()->where('name', '=', $role)->exists()) {
            return $next($request);
        }

        return redirect('/')->with('error','You have not admin access');
    }
```

also middelware added to routeMiddleware

**Comment by raul-mg** [comment]
same happend to me, for unknow reason cant get user inside middleware called from the route, I test with some random route and middleware works but fail with LogViewer route conf

**Comment by raul-mg** [comment]
Ok, I already found my error, You just need add "web" middleware before your role middleware try this:
ARCANEDEV_LOGVIEWER_MIDDLEWARE=web,role:admin

It works for me
