### ISSUE TITLE
Array to string conversion problem : @lang('Header')

### ISSUE THREAD

**Issue by sudhanshu-mittal** [ARCANEDEV/LogViewer#426]
- LogViewer Version: 9.0.0
- Laravel Version: 9
- PHP Version: 8.1

Description:
 I am getting an Array to string conversion error in @lang('Header'). How can I solve this?

![Screenshot 2022-11-30 at 11 17 51 AM](https://user-images.githubusercontent.com/85557594/204717677-08fc0201-b82a-4afb-b9e5-2b81686a7357.png)

**Comment by arcanedev-maroc** [comment]
Check your translation/lang files and choose another name for "Header" or edit the logviewer views to solve the issue
