### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by idrisalshikh** [ARCANEDEV/LogViewer#429]
- LogViewer Version: 9
- Laravel Version: 10
- PHP Version:8.1

### Description:
can't upgrade to laravel 10

### Steps To Reproduce:
composer update 
### error
 Problem 1
    - Root composer.json requires arcanedev/log-viewer 9.0 -> satisfiable by arcanedev/log-viewer[9.0.0].
    - arcanedev/support 9.0.0 requires illuminate/support ^9.0 -> satisfiable by illuminate/support[v9.0.0, ..., v9.52.0].
    - Only one of these can be installed: illuminate/support[v5.4.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0, v10.0.0], laravel/framework[v10.0.0]. laravel/framework replaces illuminate/support and thus cannot coexist with it.     
    - arcanedev/log-viewer 9.0.0 requires arcanedev/support ^9.0 -> satisfiable by arcanedev/support[9.0.0].
    - Root composer.json requires laravel/framework ^10.0 -> satisfiable by laravel/framework[v10.0.0].

**Comment by neoteknic** [comment]
+1, maybe just change the composer file ?

**Comment by suisseworks** [comment]
i get the same error

**Comment by repat** [comment]
@arcanedev-maroc Could you update the underlying library so we can update to Laravel 10? :)

Thanks!

**Comment by arcanedev-maroc** [comment]
Closed: #433
