### ISSUE TITLE
Time label - wrong regex

### ISSUE THREAD

**Issue by balping** [ARCANEDEV/LogViewer#43]
Hi!

I have this line in my logfile: 

```
[2016-01-25 08:57:54] local.INFO: Important event date set to 2016-01-17 15:00:00
```

However in log viewer in the daily view, the `time` column shows 15:00:00 instead of 08:57:54. It could be a regex problem I guess.

**Comment by balping** [comment]
Maybe a global slag should be added here?

https://github.com/ARCANEDEV/LogViewer/blob/0802fe7134f80bb48714499706f99fa7eb5c0c01/helpers.php#L61

**Comment by arcanedev-maroc** [comment]
Hi @balping, thanks for your feedback. 

I'm going to check that because there is also the [LogParser](https://github.com/ARCANEDEV/LogViewer/blob/master/src/Utilities/LogParser.php) class beside the date helpers.

**Comment by arcanedev-maroc** [comment]
Try to update the `arcanedev/log-viewer` to `>= 3.7.7` to see if the issue is fixed.

**Comment by balping** [comment]
:+1:
