### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by aschwin** [ARCANEDEV/LogViewer#44]
Hi,
I am using the Laravel 5 Boilerplate package. It has your package as one of the dependencies within the admin area.
As soon as the log file is empty (which should be a good thing) I get the following error:
`local.ERROR: ErrorException: Division by zero in ../vendor/arcanedev/log-viewer/src/Http/Controllers/LogViewerController.php:186`
I guess the `$count` variable is not checked as being zero or not and thus dividing by it does not make sense if it is a zero.

Minor issue, but can be a big problem.

**Comment by arcanedev-maroc** [comment]
Hi @aschwin, thanks for your feedback.
 
Why you delete the log file content ?

**Comment by aschwin** [comment]
Well, while developing I rather keep my logs clean and up to date. So, I delete the contents quite often to spot the new feedback much quicker.
In production this should not happen off course.

**Comment by arcanedev-maroc** [comment]
Try to delete the file instead of the content because this is the expected behavior.

But my advise for the dev environment is to switch the log system to `single`, that way you're going to avoid having multiple empty log files.

**Comment by arcanedev-maroc** [comment]
I've fixed the issue, this patch is gonna be available in the next release `> 3.7.7`.

**Comment by aschwin** [comment]
Awesome! Thanks.
