### ISSUE TITLE
Laravel 11 - Error installing

### ISSUE THREAD

**Issue by MGeurts** [ARCANEDEV/LogViewer#454]
- LogViewer Version: 11.0.0
- Laravel Version: 11.0
- PHP Version: 8.3.0

### Description:
Erro installing in fresh Laravel 11 project

### Steps To Reproduce:

- Create fresh laravel 11 project
- composer require laravel/ui --dev
- php artisan ui bootstrap --auth
- composer require arcanedev/log-viewer 

`composer require arcanedev/log-viewer       
./composer.json has been updated
Running composer update arcanedev/log-viewer
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking arcanedev/log-viewer (11.0.0)
  - Locking arcanedev/support (11.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Downloading arcanedev/support (11.0.0)
  - Downloading arcanedev/log-viewer (11.0.0)
  - Installing arcanedev/support (11.0.0): Extracting archive
  - Installing arcanedev/log-viewer (11.0.0): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   InvalidArgumentException 

  Attribute [auth] does not exist.

  at vendor\laravel\framework\src\Illuminate\Routing\RouteRegistrar.php:112
    108▕      */
    109▕     public function attribute($key, $value)
    110▕     {
    111▕         if (! in_array($key, $this->allowedAttributes)) {
  ➜ 112▕             throw new InvalidArgumentException("Attribute [{$key}] does not exist.");
    113▕         }
    114▕
    115▕         if ($key === 'middleware') {
    116▕             foreach ($value as $index => $middleware) {

  1   vendor\laravel\framework\src\Illuminate\Routing\Router.php:1502
      Illuminate\Routing\RouteRegistrar::attribute("auth", [])

  2   vendor\laravel\framework\src\Illuminate\Support\Facades\Auth.php:96
      Illuminate\Routing\Router::__call("auth")

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

**Comment by arcanedev-maroc** [comment]
This is unrelated to this package.

The issue is related to laravel ui package, i recommend using Laravel Breeze or Jetstream instead

[Read the introduction about](https://github.com/laravel/ui?tab=readme-ov-file#introduction)

> This legacy package is a very simple authentication scaffolding built on the Bootstrap CSS framework. While it continues to work with the latest version of Laravel, you should consider using [Laravel Breeze](https://github.com/laravel/breeze) for new projects. Or, for something more robust, consider [Laravel Jetstream](https://github.com/laravel/jetstream).

**Comment by MGeurts** [comment]
The laravel ui package is still supported and needed if you want a Laravel application with authentication and need to use bootstrap instead of tailwind.

Strange that this error is unrelated to LogViewer, because my laravel 11 application works just fine, as long as I don't install LogViewer.

**Comment by arcanedev-maroc** [comment]
I will try the new route registration and see if it solves the issue for you

**Comment by arcanedev-maroc** [comment]
@MGeurts Can you try the latest release?

**Comment by MGeurts** [comment]
@arcanedev-maroc Works like a charm. Thank you.
