### ISSUE TITLE
Add support for context and extra information

### ISSUE THREAD

**Issue by Mesaph** [ARCANEDEV/LogViewer#47]
Right now, the `%context%` `%extra%` are just displayed as part of the `%message%`.

It would be nice to be able to access this information in a similar way as the call stack.

**Comment by arcanedev-maroc** [comment]
Hi @Mesaph, can you make a pull request ?

**Comment by Mesaph** [comment]
Haven't looked at the code yet. Will try to do so, though.

**Comment by Mesaph** [comment]
Judging from the log files, this does not seem to be possible with the LineFormatter.

Messages are formatted as: `"[%datetime%] %channel%.%level_name%: %message% %context% %extra%\n";`

It is possible to distinguish whether `%extra%` is provided by counting the spaces at the end of the line.
It is possible to distinguish whether `%context%` is provided, if `%extra%` is not provided, by counting the spaces at the end of the line.

However, neither for `%extra%` nor for `%context%` it is possible to find out where the string should be split to get the `%message`, `%context%` and `%extra%` parts. Both `%context%` and `%extra%` are provided as json, and i don't think it is feasible to construct a regular expression that is able to match arbitrary json data.

It would be easier if the user were to use another Formatter though. Especially the JsonFormatter would be easy to parse.

If the formatter is specified in the config file, one could just select an appropriate LogParser.

Any thoughts on that?

**Comment by arcanedev-maroc** [comment]
OK i see. Try to create some getters for the [LogEntry](https://github.com/ARCANEDEV/LogViewer/blob/master/src/Entities/LogEntry.php) instead of updating the LogParser.

So the new methods will be `getMessage()`, `getContext()`, `getExtra()` and they're using regex to extract the content from the `$header` or `$stack` properties.

I think this is the easy way to implement these features.

**Comment by Mesaph** [comment]
I'm confused.
As I said, I don't think it is feasible to identify the json parts of the message using regular expressions, as they can be arbitrarily complex.

**Comment by arcanedev-maroc** [comment]
OK, i'm going to leave this issue open and see if anyone could find a work around.
