### ISSUE TITLE
can I do this with the middleware configuration?

### ISSUE THREAD

**Issue by vesper8** [ARCANEDEV/LogViewer#49]
Hey there, first of all I love your library! Use it every day and it's just great the way it is!

I noticed there's a middleware configuration and I was wondering if I could use it to accomplish what I'm trying to do in a clean way.

On my dev environment I want to push all the error messages to a redis channel. There's probably some dirty ways I could accomplish this but was wondering if I could do it using your extension and the middleware config.

I just need a place to basically add my little redis logging function. I still want the errors to be written to the log files like usual but I want to also push them on redis. I've never used a middleware yet, could you possibly take a moment to show me how I might accomplish this please?

Let's say my function is LiveLog::pushLog($errorStr);

Thanks!!

**Comment by vesper8** [comment]
Hrm.. I just setup my first middleware.. wasn't very hard :)

I'm printing out the $request and logging it in redis and it looks like this middleware is only visited when I visit the log-viewer routes... not when there's an actual error logged.. so that's no good for what I want to do...

Is there another way to accomplish what I want to do this in a clean way using your library?

**Comment by arcanedev-maroc** [comment]
Yeah the middleware is easy to setup, check out the Laravel documentations : https://laravel.com/docs/5.1/middleware.

When you put your middleware name in your `log-viewer` config file, it's gonna apply in all the log-viewer routes.

If you want to catch the errors and logged them, read about the exception handler : https://laravel.com/docs/5.1/errors#the-exception-handler
