### ISSUE TITLE
All class files not exists

### ISSUE THREAD

**Issue by Leandro-b-03** [ARCANEDEV/LogViewer#52]
Hi,

I'm trying to add the package to my app, but all the commands that I run return that the class does not exists

> [InvalidArgumentException]
> There are no commands defined in the "log-viewer" namespace.

The composer install runs OK, the config/app.php is also.
I search over here and found nothing like that, so I think I am the first in with this.

Here some thinks that may help.

Env:
> System: Windows 10 build 14267
> PHP: 7.0.0
> Mysql: 5.6

Laravel 5.1.30

```php
// config/app.php:
'providers' => [

    /*
     * Development Service Providers...
     */
    Barryvdh\Debugbar\ServiceProvider::class,

    /*
     * Laravel Framework Service Providers...
     */
    Illuminate\Foundation\Providers\ArtisanServiceProvider::class,
    Illuminate\Auth\AuthServiceProvider::class,
    Illuminate\Broadcasting\BroadcastServiceProvider::class,
    Illuminate\Bus\BusServiceProvider::class,
    Illuminate\Cache\CacheServiceProvider::class,
    Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
    Illuminate\Routing\ControllerServiceProvider::class,
    Illuminate\Cookie\CookieServiceProvider::class,
    Illuminate\Database\DatabaseServiceProvider::class,
    Illuminate\Encryption\EncryptionServiceProvider::class,
    Illuminate\Filesystem\FilesystemServiceProvider::class,
    Illuminate\Foundation\Providers\FoundationServiceProvider::class,
    Illuminate\Hashing\HashServiceProvider::class,
    Illuminate\Mail\MailServiceProvider::class,
    Illuminate\Pagination\PaginationServiceProvider::class,
    Illuminate\Pipeline\PipelineServiceProvider::class,
    Illuminate\Queue\QueueServiceProvider::class,
    Illuminate\Redis\RedisServiceProvider::class,
    Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
    Illuminate\Session\SessionServiceProvider::class,
    Illuminate\Translation\TranslationServiceProvider::class,
    Illuminate\Validation\ValidationServiceProvider::class,
    Illuminate\View\ViewServiceProvider::class,
    Illuminate\Html\HtmlServiceProvider::class,

    /*
     * Application Service Providers...
     */
    App\Providers\AppServiceProvider::class,
    App\Providers\EventServiceProvider::class,
    App\Providers\RouteServiceProvider::class,

    /*
     * Custom Services Providers...
     */
    Arcanedev\LogViewer\LogViewerServiceProvider::class,
    Collective\Html\HtmlServiceProvider::class,
    Cviebrock\EloquentSluggable\SluggableServiceProvider::class,
    Vinkla\Pusher\PusherServiceProvider::class,
    Zizaco\Entrust\EntrustServiceProvider::class,
    Intervention\Image\ImageServiceProvider::class,
    MaddHatter\LaravelFullcalendar\ServiceProvider::class,
    Laravel\Socialite\SocialiteServiceProvider::class,
    Torann\GeoIP\GeoIPServiceProvider::class,
    Alexpechkarev\GoogleGeocoder\GoogleGeocoderServiceProvider::class,
    Dsdevbe\LdapConnector\LdapConnectorServiceProvider::class,
    Maatwebsite\Excel\ExcelServiceProvider::class,

    /*
     * Personalization Services Providers...
     */
    Aws\Laravel\AwsServiceProvider::class,

    /*
     * Automation Services Providers...
     */
    Orangehill\Iseed\IseedServiceProvider::class,

    /*
     * My Services Providers...
     */
    App\Providers\HelperServiceProvider::class,

],
```

Anything that may help is appreciate!

Regards, Leandro.

**Comment by arcanedev-maroc** [comment]
Hi @Leandro-b-03, thanks for your feedback.

I'm going to check that and see what's the issue.

Stay tuned :+1: .

**Comment by arcanedev-maroc** [comment]
OK, can you check that you're using the latest `log-viewer` version (3.7.9).

Because i cannot reproduce your issue.

And to make sure that the issue is not related to the `log-viewer`, try to comment the unrelated laravel service provider and leave only the LogViewer service provider, like this:

```php
'providers' => [

    /*
     * Development Service Providers...
     */
    // Barryvdh\Debugbar\ServiceProvider::class,

    /*
     * Laravel Framework Service Providers...
     */
    Illuminate\Foundation\Providers\ArtisanServiceProvider::class,
    Illuminate\Auth\AuthServiceProvider::class,
    Illuminate\Broadcasting\BroadcastServiceProvider::class,
    Illuminate\Bus\BusServiceProvider::class,
    Illuminate\Cache\CacheServiceProvider::class,
    Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
    Illuminate\Routing\ControllerServiceProvider::class,
    Illuminate\Cookie\CookieServiceProvider::class,
    Illuminate\Database\DatabaseServiceProvider::class,
    Illuminate\Encryption\EncryptionServiceProvider::class,
    Illuminate\Filesystem\FilesystemServiceProvider::class,
    Illuminate\Foundation\Providers\FoundationServiceProvider::class,
    Illuminate\Hashing\HashServiceProvider::class,
    Illuminate\Mail\MailServiceProvider::class,
    Illuminate\Pagination\PaginationServiceProvider::class,
    Illuminate\Pipeline\PipelineServiceProvider::class,
    Illuminate\Queue\QueueServiceProvider::class,
    Illuminate\Redis\RedisServiceProvider::class,
    Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
    Illuminate\Session\SessionServiceProvider::class,
    Illuminate\Translation\TranslationServiceProvider::class,
    Illuminate\Validation\ValidationServiceProvider::class,
    Illuminate\View\ViewServiceProvider::class,
    Illuminate\Html\HtmlServiceProvider::class,

    /*
     * Application Service Providers...
     */
    App\Providers\AppServiceProvider::class,
    App\Providers\EventServiceProvider::class,
    App\Providers\RouteServiceProvider::class,

    /*
     * Custom Services Providers...
     */
    Arcanedev\LogViewer\LogViewerServiceProvider::class,
    // Collective\Html\HtmlServiceProvider::class,
    // Cviebrock\EloquentSluggable\SluggableServiceProvider::class,
    // Vinkla\Pusher\PusherServiceProvider::class,
    // Zizaco\Entrust\EntrustServiceProvider::class,
    // Intervention\Image\ImageServiceProvider::class,
    // MaddHatter\LaravelFullcalendar\ServiceProvider::class,
    // Laravel\Socialite\SocialiteServiceProvider::class,
    // Torann\GeoIP\GeoIPServiceProvider::class,
    // Alexpechkarev\GoogleGeocoder\GoogleGeocoderServiceProvider::class,
    // Dsdevbe\LdapConnector\LdapConnectorServiceProvider::class,
    // Maatwebsite\Excel\ExcelServiceProvider::class,

    /*
     * Personalization Services Providers...
     */
    // Aws\Laravel\AwsServiceProvider::class,

    /*
     * Automation Services Providers...
     */
    // Orangehill\Iseed\IseedServiceProvider::class,

    /*
     * My Services Providers...
     */
    // App\Providers\HelperServiceProvider::class,

],
```

**Comment by Leandro-b-03** [comment]
Here,
Thanks for the quick answer, well I'm do what you ask, and not worked, also remove, clean the folders and reinstall it, just to make sure, but still the same error happens.

Check my log:

> D:\Projetos\Controle-de-Horas>composer remove arcanedev/log-viewer
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
>   - Removing arcanedev/log-viewer (3.7.9)
> Writing lock file
> Generating autoload files
> > php artisan clear-compiled
> > php artisan optimize
> Generating optimized class loader
>
> D:\Projetos\Controle-de-Horas>composer require arcanedev/log-viewer
> Using version ^3.7 for arcanedev/log-viewer
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
>  - Installing arcanedev/log-viewer (3.7.9)
>    Loading from cache
>
> Writing lock file
> Generating autoload files
> > php artisan clear-compiled
> > php artisan optimize
> Generating optimized class loader
>
> D:\Projetos\Controle-de-Horas>php artisan log-viewer:publish
>
>  [InvalidArgumentException]
>  There are no commands defined in the "log-viewer" namespace.
>
> D:\Projetos\Controle-de-Horas>

I'm start think that the problem isn't the package, but other think like Laravel or Composer.

**Comment by arcanedev-maroc** [comment]
Try to run `php artisan` and see if you can get all artisan commands, and especially the `log-viewer:publish` command.

**Comment by Leandro-b-03** [comment]
The list:

D:\Projetos\Controle-de-Horas>php artisan
Laravel Framework version 5.1.31 (LTS)

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under.
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  clear-compiled      Remove the compiled class file
  down                Put the application into maintenance mode
  env                 Display the current framework environment
  help                Displays help for a command
  inspire             Display an inspiring quote
  iseed               Generate seed file from table
  list                Lists commands
  migrate             Run the database migrations
  optimize            Optimize the framework for better performance
  serve               Serve the application on the PHP development server
  tinker              Interact with your application
  up                  Bring the application out of maintenance mode
 app
  app:name            Set the application namespace
 auth
  auth:clear-resets   Flush expired password reset tokens
 cache
  cache:clear         Flush the application cache
  cache:table         Create a migration for the cache database table
 config
  config:cache        Create a cache file for faster configuration loading
  config:clear        Remove the configuration cache file
 db
  db:seed             Seed the database with records
 debugbar
  debugbar:clear      Clear the Debugbar Storage
 entrust
  entrust:classes     Creates Role and Permission classes
  entrust:migration   Creates a migration following the Entrust specifications.
 event
  event:generate      Generate the missing events and listeners based on registration
 geoip
  geoip:update        Update geoip database files to the latest version
 handler
  handler:command     Create a new command handler class
  handler:event       Create a new event handler class
 key
  key:generate        Set the application key
 make
  make:command        Create a new command class
  make:console        Create a new Artisan command
  make:controller     Create a new resource controller class
  make:event          Create a new event class
  make:job            Create a new job class
  make:listener       Create a new event listener class
  make:middleware     Create a new middleware class
  make:migration      Create a new migration file
  make:model          Create a new Eloquent model class
  make:policy         Create a new policy class
  make:provider       Create a new service provider class
  make:request        Create a new form request class
  make:seeder         Create a new seeder class
  make:test           Create a new test class
 migrate
  migrate:install     Create the migration repository
  migrate:refresh     Reset and re-run all migrations
  migrate:reset       Rollback all database migrations
  migrate:rollback    Rollback the last database migration
  migrate:status      Show the status of each migration
 queue
  queue:failed        List all of the failed queue jobs
  queue:failed-table  Create a migration for the failed queue jobs database table
  queue:flush         Flush all of the failed queue jobs
  queue:forget        Delete a failed queue job
  queue:listen        Listen to a given queue
  queue:restart       Restart queue worker daemons after their current job
  queue:retry         Retry a failed queue job
  queue:subscribe     Subscribe a URL to an Iron.io push queue
  queue:table         Create a migration for the queue jobs database table
  queue:work          Process the next job on a queue
 route
  route:cache         Create a route cache file for faster route registration
  route:clear         Remove the route cache file
  route:list          List all registered routes
 schedule
  schedule:run        Run the scheduled commands
 session
  session:table       Create a migration for the session database table
 sluggable
  sluggable:table     Create a migration for the Sluggable database columns
 vendor
  vendor:publish      Publish any publishable assets from vendor packages
 view
  view:clear          Clear all compiled view files

**Comment by arcanedev-maroc** [comment]
I don't know what is your issue because i cannot reproduce it.

I think there is something wrong with your laravel installation or other packages incompatibility.

The last thing to check is this: https://github.com/ARCANEDEV/LogViewer/blob/master/src/LogViewerServiceProvider.php#L60-L62

I think the `$this->app->runningInConsole()` is not working in your case.

If you want to publish the log-viewer assets and stuff, run this command: `php artisan vendor:publish --provider="Arcanedev\\LogViewer\\LogViewerServiceProvider"`.

**Comment by Leandro-b-03** [comment]
Hahaha I see, I can imagine that's something like that, I try to run that last line, and give me: 'Nothing to publish for tag [].', I'm think there's something wrong with my laravel installation, I will debug with careful what's happen.

So thanks a lot for the quick answers, it's very cool of you.

**Comment by arcanedev-maroc** [comment]
You're welcome :+1:

**Comment by glendlockhart** [comment]
I am having the same issue. I am on windows 10, Laravel 5.1.
All the install seems to work, but publish fails in the same way. 
Any idea of a solution ? Thanks. Glen

**Comment by Leandro-b-03** [comment]
I have tried to make a clean/fresh install and require only the log-viewer, but it doesn't work in the same way, But I'm think that is far more than a simple issue, because the same happen with Intervention/Image as well, the Laravel cannot find the path to it.

**Comment by arcanedev-maroc** [comment]
Can anyone try to debug the issue and send me the error stack/message ?

Because i cannot reproduce it locally and even [Travis CI passes the tests without a problem](https://travis-ci.org/ARCANEDEV/LogViewer/builds/110917752) (And yes, i have test units for log-viewer commands).

**Comment by glendlockhart** [comment]
Agreed. I have tried on another Laravel 5.1 app on my set up (win10) and it all works well. 

My broken app uses these packages.
  "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "league/fractal": "^0.12.0",
        "lucadegasperi/oauth2-server-laravel": "5.0.*@dev",
        "aura-is-here/laravel-multi-tenant": "dev-master",
        "barryvdh/laravel-ide-helper": "^2.1",
        "nesbot/carbon": "^1.20",
        "arcanedev/log-viewer": "~3.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"

this might help someone in the future.

**Comment by arcanedev-maroc** [comment]
Hi @glendlockhart, the `"laravel/framework": "5.1.",` dependency miss a `*` at the end => `"5.1.*"`.

**Comment by glendlockhart** [comment]
not really sure how to do a stack trace - as its unclear where things go wrong.

I get this when trying to run  the php artisan log-viewer:publish

Don't suppose that's too helpful. 

[2016-03-03 12:25:54] local.ERROR: exception 'InvalidArgumentException' with message 'There are no commands defined in the "log-viewer" namespace.' in C:\xampp\htdocs\mht-api\vendor\symfony\console\Application.php:469
Stack trace:
#0 C:\xampp\htdocs\mht-api\vendor\symfony\console\Application.php(501): Symfony\Component\Console\Application->findNamespace('log-viewer')
#1 C:\xampp\htdocs\mht-api\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->find('log-viewer:publ...')
#2 C:\xampp\htdocs\mht-api\vendor\symfony\console\Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\xampp\htdocs\mht-api\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\xampp\htdocs\mht-api\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}

**Comment by arcanedev-maroc** [comment]
Did you added the `Arcanedev\LogViewer\LogViewerServiceProvider::class,` provider in your `config/app.php` ?

**Comment by arcanedev-maroc** [comment]
@Leandro-b-03 @glendlockhart, i think i've found something about this issue. [Check this thread](http://laravel.io/forum/06-17-2014-artisan-cronjob-there-are-no-commands-defined-in-the-xyz-namespace).

As you can see, the `log-viewer` has a [dedicated commands service provider](https://github.com/ARCANEDEV/LogViewer/blob/master/src/LogViewerServiceProvider.php#L60-L62), and to register the commands, the [$this->app->runningInConsole()](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Application.php#L482-L485) must return `true`.

So, this is related to your hosting setup.

**Comment by glendlockhart** [comment]
oh contraire mon frere !
I have 2 projects running locally on xampp. It works on one but not the other !
So almost certainly not that issue for me.
But thank you for the speedy responses guys, I appreciate the helps.

**Comment by arcanedev-maroc** [comment]
C'est avec plaisir bro :+1:

**Comment by Leandro-b-03** [comment]
@arcanedev-maroc, It turns out I'm already on php-cli:

> PHP 7.0.0 (cli) (built: Dec  3 2015 11:36:59) ( ZTS )
> Copyright (c) 1997-2015 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies

@glendlockhart, =)

**Comment by arcanedev-maroc** [comment]
Try to edit the `routes.php` by adding `dd(php_sapi_name(), App::runningInConsole());`, and run `php artisan`, you should see `"cli"` and `true`.

If you got different values, try remove the `if ($this->app->runningInConsole()) { ... }` and leave ` $this->app->register('Arcanedev\\LogViewer\\Providers\\CommandsServiceProvider');` in [LogViewerServiceProvider](https://github.com/ARCANEDEV/LogViewer/blob/master/src/LogViewerServiceProvider.php#L60-L62) located in your `vendor/arcanedev/log-viewer`.

**Comment by glendlockhart** [comment]
got it working now.

So, I copied the config\log-viewer.php from my other project
I then moved the provider higher up my list in so it looked like this:

  /*
        * Third party providers
        */
        Arcanedev\LogViewer\LogViewerServiceProvider::class,
        'LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider',
        'LucaDegasperi\OAuth2Server\OAuth2ServerServiceProvider',
        'AuraIsHere\LaravelMultiTenant\LaravelMultiTenantServiceProvider',
        Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,


run the publish command again - and it jumped into life.

Hope this help. 
Great package arc, thanks for the support

Glen

**Comment by arcanedev-maroc** [comment]
Glad that you resolve your issue @glendlockhart,

![](http://weknowmemes.com/wp-content/uploads/2012/09/my-code-doesnt-work-i-have-no-idea-why.jpg)

But i'm still curious about this issue, can you delete the `log-viewer` config file and see if it still working ?

**Comment by glendlockhart** [comment]
So, now I can't get it to break ! 
I have removed the config file and it regenerates with no problem. I have even moved the order of the providers in the config and it still works.

Sorry,  see above meme :-)

**Comment by Leandro-b-03** [comment]
By doing what the @glendlockhart says, the package work on the clean Laravel's folder, but not on my current project.
And by putting the log files on the project that worked thats is the stack trace:

Stack trace:
#0 F:\Projetos\Controle-de-Horas\vendor\symfony\console\Application.php(501): Symfony\Component\Console\Application->findNamespace('log-viewer')
#1 F:\Projetos\Controle-de-Horas\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->find('log-viewer:publ...')
#2 F:\Projetos\Controle-de-Horas\vendor\symfony\console\Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 F:\Projetos\Controle-de-Horas\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 F:\Projetos\Controle-de-Horas\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}


Haha, I wrote the line on routes.php and cli is equals true =)

**Comment by Leandro-b-03** [comment]
After a long debug days, I found, what happens was very, but very simple, the laravel + php cache was not generating the correct one after the > php artisan clear-compiled and the > composer dump-autoload (-o), hahaha feel like dump one, after all, but the correction (to this) is clear the cached files a > php artisan cache:clear and > php artisan config:cache, I think and deleted all the cached files on storage folder, now it's working like a charm.

Thanks all for the patience and the promptitude for the issue, let the legacy run over us =), like we say here in Brazil, Living and learning, < literal translation;

**Comment by jcsto** [comment]
Hey, I solved it this way, thanks to @cviebrock,
just have to use instead the artisan command:
1- php artisan make:migration name_of_the_migration
**make adjustments in the migrated file**
      public function up(){
            Schema::table('nameOfTable', function(Blueprint $table){
                    $table->string('slug')->nullable();
             });
      }
      public function down(){
            Schema::table('nameOfTable', function(Blueprint $table){
                    $table->dropColumn('slug');
             });
      }

and then;
2- php artisan migrate

Done!
