### ISSUE TITLE
JS error when trying to delete log in 3.8.0

### ISSUE THREAD

**Issue by tianissimo** [ARCANEDEV/LogViewer#54]
In logs.blade.php, the single quotes are missing in the selector `$("a[href=#delete-log-modal]")`. It should be `$("a[href='#delete-log-modal']")`

**Comment by arcanedev-maroc** [comment]
Which browser you're using ?

**Comment by tianissimo** [comment]
I found out that the selector like that doesn't work with jQuery 2.2.x but It works fine with 2.1

**Comment by arcanedev-maroc** [comment]
OK, i'm going to close this issue because it's unrelated to this package.

And also, you can edit the resource files to solve it.
