### ISSUE TITLE
No hint path defined for [log-viewer] Error

### ISSUE THREAD

**Issue by rocandante** [ARCANEDEV/LogViewer#55]
I just tried this package in laravel 5.1 but I getting an error when I go to /log-viewer on my project:

    InvalidArgumentException in FileViewFinder.php line 112: No hint path defined for [log-viewer].

    in FileViewFinder.php line 112
    at FileViewFinder->getNamespaceSegments('log-viewer::dashboard') in FileViewFinder.php line 90
    at FileViewFinder->findNamedPathView('log-viewer::dashboard') in FileViewFinder.php line 76
    at FileViewFinder->find('log-viewer::dashboard') in Factory.php line 151

I followed the steps given in the wiki and the command: php artisan route:list, list all routes:

    GET|HEAD | log-viewer                      | log-viewer::dashboard     | Arcanedev\LogViewer\Http\Controllers\LogViewerController@index
    GET|HEAD | log-viewer/logs                 | log-viewer::logs.list     | Arcanedev\LogViewer\Http\Controllers\LogViewerController@listLogs    |            |
    DELETE   | log-viewer/logs/delete          | log-viewer::logs.delete   | Arcanedev\LogViewer\Http\Controllers\LogViewerController@delete      |            |
    GET|HEAD | log-viewer/logs/{date}          | log-viewer::logs.show     | Arcanedev\LogViewer\Http\Controllers\LogViewerController@show        |            |
    GET|HEAD | log-viewer/logs/{date}/download | log-viewer::logs.download | Arcanedev\LogViewer\Http\Controllers\LogViewerController@download    |            |
    GET|HEAD | log-viewer/logs/{date}/{level}  | log-viewer::logs.filter   | Arcanedev\LogViewer\Http\Controllers\LogViewerController@showByLevel

I have package's version 3.7.9. Can someone help with this issue?

**Comment by arcanedev-maroc** [comment]
Try to use the latest version (3.8.0) by editing your composer.json `"arcanedev/log-viewer": "~3.0"` and see if it's going to fix your issue.

By the way we don't have wiki, we have the [docs folder](https://github.com/ARCANEDEV/LogViewer/tree/master/_docs) instead.

**Comment by rocandante** [comment]
I edited composer.json file and try update but composer say: Nothing to install or update. 

I think this error is because I use themes and the paths are registered through FileViewFinder, may need to register the package's routes there. Reach this conclusion because in a fresh installation of laravel all worked well for me.

Yep, you right about wiki, my mistake, I meant installation guide.

I'm googling a bit more to see that I can fix, I also go to try making my own views.

Thanks for the reply

**Comment by arcanedev-maroc** [comment]
OK, i understand your issue now and it's not a bug related to `log-viewer` package.

Did you changed [this method](https://github.com/laravel/framework/blob/5.2/src/Illuminate/View/ViewServiceProvider.php#L90-L97) ? can you provide me some information ?

Try to leave the [default views folder path](https://github.com/laravel/laravel/blob/master/config/view.php#L17) and add your custom themes paths next to it like this:

```php
    'paths' => [
        realpath(base_path('resources/views')),
        realpath(base_path('resources/themes')), // or something else
    ],
```

Or try to restructure your folders like this.

```
resources/
    |-- assets/
    |-- lang/
    |-- views/
    |     |-- themes/
    |     |     |-- default/
    |     |     |-- dark/
    |     |     |-- light/
    |     |     |-- monokai/
    |     |-- vendor/
    |    ...
   ...
```
And leave the `config/views.php` as default.

If you remove the default views path from the `config/views.php` file, this may cause some issues because the package register the vendor views based on the default views path, [check this line for more details](https://github.com/ARCANEDEV/LogViewer/blob/master/src/LogViewerServiceProvider.php#L125).

**Comment by rocandante** [comment]
I have tried to resolve the issue but I'm not sure how to correctly modify the code that have related to FileViewFinder and include the path to the package. I have noticed that the view fails when called package::view but not if view name is path.view, I don't know why. I share the code use if anyone can give any clue what to do.

This is app/Providers/AppServiceProvider.php file:

    public function boot()
    {
        $this->app['view']->setFinder($this->app['theme.finder']);
    }

    public function register()
    {
      $this->app->singleton('theme.finder', function ($app) {
          $finder = new ThemeViewFinder($app['files'], $app['config']['view.paths']);

          $config = $app['config']['prado.theme'];

          $finder->setBasePath($app['path.public'].'/'.$config['folder']);
          $finder->setActiveTheme($config['active']);

          return $finder;
      });

However I have cloned the views and the controller included in Log-Viewer and used the API. It was very simple change all and everything works without any problems. Even suits views to the project's features and it looks cool:
http://imgur.com/vGasxW8

By the way, according to composer I have installed version 3.8.0 but the package returns 3.7.9. I don't know if it is a package error.

Regards and thanks for help me

**Comment by arcanedev-maroc** [comment]
You're welcome :+1: , glad that you've solved your issue.

And sorry about the LogViewer version, [i've forgot to bump it](https://github.com/ARCANEDEV/LogViewer/blob/master/src/LogViewer.php#L23), my bad :stuck_out_tongue_closed_eyes: .
