### ISSUE TITLE
Locale config ignored

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [ARCANEDEV/LogViewer#59]
Hi there!

I have the following config in `config/log-viewer.php`:

```
'locale'        => 'en',
```

But the LogViewer ignores this, and uses the default application locale, which is "pt-BR" in my case.

I would like to use "en" in LogViewer, to avoid label crashes like this one:

![lang](https://cloud.githubusercontent.com/assets/12160864/14615608/dd0a4c62-057c-11e6-8f72-aac12eaf2a34.png)

Even when publishing the lang files, the "en" locale is not loaded at all.

How to use "en" locale in LogViewer?

Best regards,
Rafael Pacheco.

**Comment by rafael-renan-pacheco** [comment]
Hello! Thanks for the fast reply.

It did not work, with and without published lang files.

```php
    public function name()
    {
        //return trans('log-viewer::levels.' . $this->level);

        $locale = config('log-viewer.locale', 'auto');
        if ($locale ===  'auto') $locale = null;

        return trans('log-viewer::levels.' . $this->level, [], 'messages', $locale);
    }
```

Will it be possible to make this work without publishing the lang files? I don't plan changing the language files.

Best regards,
Rafael Pacheco

**Comment by arcanedev-maroc** [comment]
Just give me some time to see what's exactly the issue. Stay tuned.

**Comment by arcanedev-maroc** [comment]
I think i solved the issue, try to update your `log-viewer` package to `>=3.9.0` and see if it's working for you.

**Comment by rafael-renan-pacheco** [comment]
Working perfectly now, thank you very much :grinning:
