### ISSUE TITLE
 404 error

### ISSUE THREAD

**Issue by Cannonb4ll** [ARCANEDEV/LogViewer#6]
I just tried this package in 2 laravel (5.1) installations (to be sure). I keep getting a 404 error when I go to /log-viewer on my project.

Steps I have done:

- Setup composer.json correcty
- Composer update
- Add provider to config/app.php
- Publish it through command
- Acces domain.com/log-viewer

Result 404 page

Am I missing something? Or is my routes blocking this feature?

**Comment by arcanedev-maroc** [comment]
First things first, Check if you're using LogViewer 3.0.

  - Check if `log-viewer.php` file exists in the config folder.
  - Check you don't have a route like `Route::get('{slug}', []);` in your application routes (You can change the LogViewer's uri prefix like `my/super/log/viewer`).
  - Try the package with a fresh laravel installation and see if you're going to get the same issue.

May the force be with you.

**Comment by DerJacques** [comment]
I experience the exact same issue.
Went through the mentioned troubleshooting (except for a fresh install), but unfortunately the error persists.

I'm using Laravel 5.1.
`php artisan route:list` does not display the added routes.

Let me know if I can be of any further assistance. :-)

**Comment by DerJacques** [comment]
After digging around a bit, it appears to me that the issue becomes apparent somewhere in the file `/vendor/arcanedev/support/src/Laravel/Providers/RouteServiceProvider.php`.

I found that `$pos` on line 148 is `false`, even though it seems `true` is expected. Maybe Laravel has problems reading the `LogViewerRoute.php` file?

**Comment by DerJacques** [comment]
One last remark:
When I manually add the following route to my own routes file, it "works":

`Route::get('logview', '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@index');`

I'm putting "works" in quotation marks, because I now receive this error: `Route [log-viewer::dashboard] not defined.`
I guess that's to be expected, since I only defined this one route.

**Comment by arcanedev-maroc** [comment]
Ok, i'm going to fix the RouteServiceProvider from `arcanedev/support, because there is an issue with RecursiveDirectoryIterator (on Windows, works perfectely).

Yeah you need to add route name

```php
// log-viewer or any prefix
Route::get('log-viewer', [ 
    'as'   => 'log-viewer::dashboard',
    'uses' => '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@index',
]);
```

you can also do this to register all routes:
```php
// routes.php
(new Arcanedev\LogViewer\Http\Routes\LogViewerRoute)->map(app(''router''));
```

**Comment by georgeboot** [comment]
You can fix this temporary by adding this to your `routes.php`:

```php
// Log Viewer
Route::get('log-viewer', [
    'as'   => 'log-viewer::dashboard',
    'uses' => '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@index',
]);

Route::group(['prefix' => 'logs'], function() {
    Route::get('/', [
        'as'    => 'log-viewer::logs.list',
        'uses'  => '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@listLogs',
    ]);
    Route::delete('delete', [
        'as'    => 'log-viewer::logs.delete',
        'uses'  => '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@delete',
    ]);

    Route::group(['prefix' => '{date}'], function() {
        Route::get('/', [
            'as'    => 'log-viewer::logs.show',
            'uses'  => '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@show',
        ]);
        Route::get('download', [
            'as'    => 'log-viewer::logs.download',
            'uses'  => '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@download',
        ]);
        Route::get('{level}', [
            'as'    => 'log-viewer::logs.filter',
            'uses'  => '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@showByLevel',
        ]);
    });
});
```

**Comment by arcanedev-maroc** [comment]
Thanks @georgeboot for your feedbacks,

I've fixed the problem https://github.com/ARCANEDEV/Support/commit/e603730820cb6b8e51b02a4cb6661c18d8771b5d (Windows vs Linux stuff).

Can you update the package and make sure you have `arcanedev\support : 2.1.4` and `arcanedev\log-viewer : 3.0.1` ?

**Comment by Cannonb4ll** [comment]
I can indeed confirm that this works on a new laravel project. But on the project I am currently working on, this is giving me conflicts with the log viewer package:

Route::controller('/','Auth\AuthController');

If I remove this route, the log-viewer works perfectly. But when I add it, I get a 404.

**Comment by arcanedev-maroc** [comment]
Try to check all routes et find where the conflict is, try this command to see all routes `php artisan route:list`.
