### ISSUE TITLE
LogViewerServiceProvider::publishConfig() must be protected 

### ISSUE THREAD

**Issue by nasirkhan** [ARCANEDEV/LogViewer#61]
I got the following error at the time of running the command `composer update`
```
Access level to Arcanedev\LogViewer\LogViewerServiceProvider::publishConfig() must be protected (as in class Arcanedev\Support\PackageServiceProvider) or weaker
```

**Comment by arcanedev-maroc** [comment]
You're using an old version, the current one is `3.9.0`.

First, try to comment the provider `Arcanedev\LogViewer\LogViewerServiceProvider` in your `app.php` config file and uncomment it after the update.
