### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by UnrulyNatives** [ARCANEDEV/LogViewer#62]
My most often want when debugging is to see the newest entry in the newest (daily) log file.

I suggest the dashboard `\log-viewer` would put the entry on the very top. 
Best solution would be automatic refresh if only a new entry would generate.

Outside of this lack, your viewer is great! Thank you!

**Comment by arcanedev-maroc** [comment]
You can do that by editing the dashboard controller/views.
