### ISSUE TITLE
Middleware is always redirecting 

### ISSUE THREAD

**Issue by kamaroly** [ARCANEDEV/LogViewer#63]
Hi, 
My I have protected access with middle ware however it is redirecting always even when someone is eligible. 
How can I fix it?
Regards

**Comment by arcanedev-maroc** [comment]
By default, the LogViewer middleware is `null`, you can see that in your [log-viewer config file](https://github.com/ARCANEDEV/LogViewer/blob/master/config/log-viewer.php#L28).

You need to check your app and especially your middleware(s).
