### ISSUE TITLE
How to view other named log files (laravel-cli-)

### ISSUE THREAD

**Issue by palpalani** [ARCANEDEV/LogViewer#65]
Recently, we faced permission issue for creating logs. So we created separate log file for cli. Our logs file names like `laravel-cli-2016-05-19.log`, `laravel-fpm-fcgi-2016-05-14`. Permission issue is resolve, but we are not able view these log files using LogViewer.

How to view those log files?

**Comment by arcanedev-maroc** [comment]
This package doesn't support this feature. The only thing you can do is to override the LogViewer classes and especially the [Filesystem Class](https://github.com/ARCANEDEV/LogViewer/blob/master/src/Utilities/Filesystem.php#L98).

**Comment by arcanedev-maroc** [comment]
Good news @palpalani, i solved your case.

You can use now the [new methods](https://github.com/ARCANEDEV/LogViewer/blob/master/src/LogViewer.php#L113-L140) to load your custom log files names.

Or by using the new config file **pattern** attributes.

Available from `arcanedev/logivewer >= 3.10.0`.

**Comment by arcanedev-maroc** [comment]
You're going to do it manually (you can use the LogViewer as an API).

1. Disable the default `LogViewer` routes.
2. Create your new log-viewer routes by using prefixes or slugs (`cli`, `fpm-fcgi`).
3. Create a new `LogViewer` Controller (You can copy some codes from the base LogViewer Controller), and use the new methods to set pattern base on prefixes/slugs.
4. Edit views and other stuff if necessary.
5. Profit :moneybag:

**Comment by palpalani** [comment]
yes, duplicated your `LogViewerController` and then assigned custom pattern value like `$this->logViewer->setPattern('laravel-web-', $date, $extension);`.

Wow! it works.

**Comment by hhhcj** [comment]
If there is a simple way to realize this feature, that must be cool.
