### ISSUE TITLE
Deleting a log that will generate a new log fails on Windows 10

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [ARCANEDEV/LogViewer#66]
Hi there!

Here is the problem:

I have a middleware enabled for LogViewer, which checks if the user has access to open and see LogViewer. This middleware runs 2 sql commands, one to load the user model, and another one to check if the user has the correct rule to view LogViewer. Since my application logs all sqls, these 2 sqls are fired for every new request and stored in laravel log file.

When serving my app In Windows 10 using XAMPP, if I try to delete the current log in LogViewer, it fails with the following exception:

![bug](https://cloud.githubusercontent.com/assets/12160864/15765464/7cf39678-290b-11e6-9fe4-3ca557e65cea.png)

I'm guessing the problem is LogViewer trying to delete the file, and Laravel trying to store new log right away. If I delete a log from yesterday, it works just fine.

Serving my app from Linux works just fine as well. The moment I delete the log file, the LogViewer page is refreshed with an already new log file with 2 info lines (those 2 sqls I said before).

This is not critical, but would be nice to work just like it works on linux (if possible :smile:)

Thanks!

**Comment by arcanedev-maroc** [comment]
Feel free to make a PR to solve this issue :+1:

I can't reproduce it because i don't have a Windows 10.

**Comment by rafael-renan-pacheco** [comment]
Hi there!

I'm returning to Linux to continue my app development, since there are many other major issues in Windows.

I'll close this issue since this is a minnor bug only during development in Windows. After deploying, usually to a linux machine, this problem will not happen. Thanks!

**Comment by arcanedev-maroc** [comment]
OK @rafael-renan-pacheco, Thanks BTW for your feedbacks :+1:
