### ISSUE TITLE
Logger always takes the latest routes.

### ISSUE THREAD

**Issue by Asvae** [ARCANEDEV/LogViewer#68]
I my `app.php` I have providers like that:
```
Arcanedev\LogViewer\LogViewerServiceProvider::class,
App\MyServiceProvider::class,
```
My provider registers the following route:
```
$router->get('{slug}', function () { return view('app'); })->where('slug', '(.*)?');
```
The problem is that despite the fact that `App\MyServiceProvider` is registered second, the lowest priority is always taken by LogViewer routes.
You can clearly see it in dump:
```
// dd(\Route::getRoutes()->getRoutesByMethod()['GET']);
  "{slug}" => Route {#167 ▶}
  "log-viewer" => Route {#170 ▶}
  "log-viewer/logs" => Route {#172 ▶}
  "log-viewer/logs/{date}" => Route {#175 ▶}
  "log-viewer/logs/{date}/download" => Route {#176 ▶}
  "log-viewer/logs/{date}/{level}" => Route {#177 ▶}
```
Any information is much appreciated.

**Comment by arcanedev-maroc** [comment]
Suggestion N°1 - Edit your condition in your route `->where('slug', '(.*)?')` to skip any slug with `log-viewer`.

Suggestion N°2 - Add a prefix to your `$router->get('{slug}', ...)`.

Suggestion N°3 - Copy and paste all log-viewer routes to your app routes and disable the old one, that way you can order them in single place.
