### ISSUE TITLE
Adding a log search for specific keyword or text in entries headers

### ISSUE THREAD

**Issue by arcanedev-maroc** [ARCANEDEV/LogViewer#7]
Worth it or not ?

**Comment by RamonSmit** [comment]
:+1:

**Comment by bloggervista** [comment]
yes worthy

**Comment by uicosp** [comment]
really need this feature!

**Comment by arcanedev-maroc** [comment]
Feel free to make a PR for this feature 👍

**Comment by uicosp** [comment]
Do some tricks by laravel collection "filter" method to support SEARCH feature. #152

**Comment by arcanedev-maroc** [comment]
Thanks @uicosp for your PR.

I'm going to review/test these changes as soon as I got some free time.

**Closed:** Discuss about this feature on PR: #152
