### ISSUE TITLE
Multiple filename supports

### ISSUE THREAD

**Issue by Silentscripter** [ARCANEDEV/LogViewer#70]
Hello and thanks for your package.
I think it would be nice if you may add support for multiple filenames in log configuration (for example by allowing regex pattern for the prefix) because the current configuration seems too rigid imo.

To clarify I've an application where there some logs divided by their responsabilities (products-2016-07-01.log, storage-2016-07-01.log). As of now I can't support them both.

Thanks in advance for your attention.

**Comment by arcanedev-maroc** [comment]
Check this: #65

**Comment by Silentscripter** [comment]
That's not the same thing I'd like to achieve as I would like to handle all files from the same view.

**Comment by arcanedev-maroc** [comment]
This is a very specific case, my advise is to use the LogViewer as an API.

Try to check the documentation & the tests folder to see how to manipulate the log entries.
