### ISSUE TITLE
view share

### ISSUE THREAD

**Issue by sannezuidema** [ARCANEDEV/LogViewer#72]
I want to include your log viewer in my own theme, but the view share in AppServiceProvider is not working. In my nav I display the name of the user, but now i get the error: Trying to get property of non-object.

**Comment by arcanedev-maroc** [comment]
Why are you using view share ?

You can update/override the LogViewer routes (via config file) and views to include it in your theme.

Check this project to see how its done : https://github.com/rappasoft/laravel-5-boilerplate
