### ISSUE TITLE
With 30M laravel log got PHP 128M bytes exhausted error

### ISSUE THREAD

**Issue by Jofator** [ARCANEDEV/LogViewer#74]
Hi there,
great plugin.
But with 7 logs 30M in total I got fail response with:

production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes)' in /mnt/data/webhosting/ftp/azpneu/StudioV2/laravel/vendor/arcanedev/log-viewer/src/Utilities/LogParser.php:91

Is is possible to fix it please?

Regards
Jan

**Comment by arcanedev-maroc** [comment]
Hi @Jofator, thanks for reporting this issue.

I think this is related to the memory limit of you PHP config. Can you check this: http://php.net/manual/en/ini.core.php#ini.memory-limit

To solve it, you need to edit your `PHP.ini` the value of `memory_limit= xxM;`.

For more details: http://stackoverflow.com/questions/415801/allowed-memory-size-of-33554432-bytes-exhausted-tried-to-allocate-43148176-byte

**Comment by Jofator** [comment]
Hi @arcanedev-maroc, it is production and I cannot edit php.ini.
I just thought 128M should be enough for 30M logs.
Dont you want try to refactor design? :)
Anyway thanks for info and have a nice day.

**Comment by arcanedev-maroc** [comment]
If you can't edit the php.ini in your production server.

You can edit the `bootstrap/autoload.php` file and adding the `ini_set('memory_limit', '256M');` at the [first line](https://github.com/laravel/laravel/blob/master/bootstrap/autoload.php#L2).

For unlimited memory usage, try `ini_set('memory_limit', '-1');`.
