### ISSUE TITLE
Auth with https://github.com/tymondesigns/jwt-auth

### ISSUE THREAD

**Issue by thiagoaos** [ARCANEDEV/LogViewer#80]
Hi,

I want to add the `jwt.auth` midleware but this middleware wait for a token, don´t use the session. How can i integrate your package with jwt auth package to works in internall calls like `http://localhost:5000/log-viewer/logs/2016-08-29`

**Comment by arcanedev-maroc** [comment]
Try to add your middleware to your 'config/log-viewer.php' config file: https://github.com/ARCANEDEV/LogViewer/blob/master/config/log-viewer.php#L41

**Comment by thiagoaos** [comment]
I already did that. But this middleware waiting for a token in header of each request and your package won´t send that.

**Comment by arcanedev-maroc** [comment]
Did you get a `Token not provided` error ??

**Comment by arcanedev-maroc** [comment]
Honestly, i have no clue about the JWT package you're using and how to solve your issue.

You need to post this issue in their repo instead because is unrelated to this package.

**Comment by thiagoaos** [comment]
Yes. {"error":"token_not_provided"}

**Comment by thiagoaos** [comment]
No, both package works very well alone, but i would like to use your package with your already done views but with his auth or any other token based auth.

**Comment by arcanedev-maroc** [comment]
What i mean by unrelated to the LogViewer package, is that your middleware is working in `log-viewer` routes. Your issue is related to JWT package, because you need to pass a token to your middleware, so you need to read their documentation and check their issues/solutions in JWT repo.
