### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by minedun6** [ARCANEDEV/LogViewer#83]
Is there a way to get some detailed documentation about customizing the layout of the dashboard to incorporate it into our own template and on how to log models activities ?

**Comment by arcanedev-maroc** [comment]
You can customize it like you customize any laravel package. 

You publish the package config/views/etc and you start to override it.

 * First you need to disable the default routes/controllers to replace it with yours ([something like this](https://github.com/ARCANESOFT/Foundation/blob/master/src/Providers/PackagesServiceProvider.php#L84-L94)).
 * For the [routes](https://github.com/ARCANESOFT/Foundation/blob/master/src/Http/Routes/LogViewerRoutes.php#L21-L63).
 * For the [controllers](https://github.com/ARCANESOFT/Foundation/blob/master/src/Http/Controllers/LogViewerController.php).
 * For the views, [check this folder](https://github.com/ARCANESOFT/Foundation/tree/master/resources/views/log-viewer).
 * And Voila!!!

You can also check the other approaches like:
 * https://github.com/rappasoft/laravel-5-boilerplate
 * https://github.com/mikimaine/ecommerce

And i know that documentation is incomplete, but you can check the [contracts folder](https://github.com/ARCANEDEV/LogViewer/tree/master/src/Contracts) or the [tests folder](https://github.com/ARCANEDEV/LogViewer/tree/master/tests) for more details.

Thanks for using this package 👍

**Comment by minedun6** [comment]
Thank you so much for the quick headsup !! ^_^
I'll try to check it out and keep you updated about my progress.
