### ISSUE TITLE
In systems not unix, like windows, GLOB_BRACE flag may cause exception

### ISSUE THREAD

**Issue by Remember2015** [ARCANEDEV/LogViewer#84]
The GLOB_BRACE flag is not available on some non GNU systems, like windows

code in \src\Utilities\Filesystem.php  line 284 

`$files = $this->filesystem->glob(
    $this->storagePath.DS.$pattern, GLOB_BRACE
);`

`GLOB_BRACE`  should be `(defined('GLOB_BRACE') ? GLOB_BRACE : 0)`

**Comment by arcanedev-maroc** [comment]
Hi @Remember2015, thanks for using this package.

Can you tell me more about this issue and how to reproduce it ?

To be honest, i'm a heavenly windows user and i've never encounter this issue.

**Comment by Remember2015** [comment]
php running in docker windows may cause this problem
