### ISSUE TITLE
Able to use gzip log files?

### ISSUE THREAD

**Issue by jonnywilliamson** [ARCANEDEV/LogViewer#89]
Hi,

My production server uses logrotate to compress and rotate my log files.

Is there any way to set up LogViewer to be able to view these? At the moment my storage log folder looks like this:

![image](https://cloud.githubusercontent.com/assets/2513663/19171115/14a8b01a-8c13-11e6-82f6-856a255a9c8a.png)

Thanks very much!

**Comment by arcanedev-maroc** [comment]
To be honest, i've no idea how `logrotate` works with Laravel.

But feel free to make a PR (with tests) if you want to add this feature.

**Comment by jonnywilliamson** [comment]
Sorry, telling you about logrotate was not actually necessary.

I think the simpler question is just, can Log-Viewer open/read compressed (gzip) log files?

**Comment by arcanedev-maroc** [comment]
For the time being, just regular `*.log` files.

**Comment by jonnywilliamson** [comment]
Ok, will have a look at this

For future reference for me:
http://stackoverflow.com/questions/18206845/file-get-contents-equivalent-for-gzipped-files
http://stackoverflow.com/a/8582042
