### ISSUE TITLE
JWT tokens?

### ISSUE THREAD

**Issue by iherbivore** [ARCANEDEV/LogViewer#90]
My Laravel server is primarily a RESTful API server. I use jwt tokens for stateless authentication. I like this log viewer a lot but can't figure out how to use it. I have a middleware that expects a token. I set an iframe that successfully loads the log viewer when I set the token on the src url. The problem is the subsequent requests from within the log viewer don't have the token and so they fail.

Is there a way to set a name/value pair on the requests the log viewer makes?

**Comment by iherbivore** [comment]
I worked it out. I only feel a little dirty. I made my own version of the `route` helper in a file named `RouteBuilder.php`

```
if (! function_exists('route')) {
    /**
     * Generate a URL to a named route.
     *
     * @param  string  $name
     * @param  array   $parameters
     * @param  bool    $absolute
     * @return string
     */
    function route($name, $parameters = [], $absolute = true)
    {
        if(strpos($name, 'log-viewer') !== false){
            $token = app('request')->input('token', 'no-token');
            $parameters['token'] = $token;
        }
        
        return app('url')->route($name, $parameters, $absolute);
    }
}
```

and loaded it prior to everything else in the `index.php`

```
require __DIR__.'/../app/Helpers/RouteBuilder.php';
require __DIR__.'/../bootstrap/autoload.php';
```

It was so close to perfect except for this in the `LogViewerController.php`

```
 if ($level === 'all')
            return redirect()->route($this->showRoute, [$date]);
```

so (my embarrasing hack step) I had to change it:

```
if ($level === 'all')
            return redirect( route($this->showRoute, [$date]));
```

Now everything seems to work. Only downfall is it doesn't really lend itself to single use tokens like I use for other requests.

**Comment by arcanedev-maroc** [comment]
Hi @iherbivore, thanks for using this package.

Did you tried to append the `token` parameter in a middleware ?

Like this:

```php
// inside the handle method
$request->attributes->set('token', $request->input('token', 'no-token'));
```

Check if this gonna works for you : http://stackoverflow.com/questions/32228176/laravel-passing-variables-from-middleware-to-controller-route

**Comment by iherbivore** [comment]
Hi @arcanedev-maroc Thanks for the great package!

I don't think that works for my situation. Every request coming in has to have a token as there is no session storage on the server. So the requests being generated from within your package have to send the token or the middleware catches it as unauthorized. 

I attach the token on my initial call to the log-view route so it is available at that point. Then all of the URLs within your package are generated via the global route helper function. So by overriding that method I can stuff in the extra token parameter for every URL your package generates. That causes it to be appended as a query parameter. 
The only sticky point was the one place where you generate the URL by a different method than the global route helper. I had to fork your project so I could pull in the version I listed above.

**Comment by arcanedev-maroc** [comment]
OK, the second solution (and the best IMO) is to override the log-viewer routes and controller instead of the `route` global function.

You just disable the default log-viewer routes and create your own routes and LogViewerController, you can copy/paste the same codes to make the changes.

And leave the `route()` function as it is.

You can check this issue for more details: https://github.com/ARCANEDEV/LogViewer/issues/83

**Comment by iherbivore** [comment]
That doesn't feel right to me. I would have to make so many changes to accomplish the exact same thing in the end. And the route URLs are primarily generated in the views so I don't see any way to do what I have done without rewriting the views as well. My change is a single point change and I would argue that the Laravel framework is intends for such changes to exist, else why would they check if the `route` function exists before defining it in the helpers.php? 

If you would be willing to change that one line in your controller life would be awesome all around. What say ye?

**Comment by arcanedev-maroc** [comment]
I don't know but i gonna think about it if i get many demands about this feature.

**Comment by iherbivore** [comment]
OK thanks, but not really a feature. just using the Laravel route helper for all your URLs. Currently you use it for all URLs except for one. You could consider this to be more consistent. :)
