### ISSUE TITLE
Allowed memory exhausted error

### ISSUE THREAD

**Issue by gr-jialeiwang** [ARCANEDEV/LogViewer#91]
hi

when i access http://{my-project}/log-viewer, there is a error come out
"Allowed memory size of 67108864 bytes exhausted (tried to allocate 8388616 bytes) "
and it happened in "log-viewer/src/Helpers/LogParser.php:71 preg_match_all()".

i can edit my php.ini to increase memory for a while,
but in future if log files go to bigger then 
i have to edit  php.ini  to  increase memory again

can i not read all log files , for example , only read last 10 log files  or last 7days log files?

Regards

**Comment by arcanedev-maroc** [comment]
Can you make these changes and see if it solves your issue ?

PR: https://github.com/ARCANEDEV/LogViewer/pull/87/files

**Comment by gr-jialeiwang** [comment]
hi

thank you 

my project is online now so i only can use "composer update" command in middle of the night
if i edit composer.json to checkout patch-memory_enhacements branch to test,
then after the test i have to edit composer.json again 
that means i have to composer update twice 

so can you merge your source to master branch?

**Comment by arcanedev-maroc** [comment]
I'm going to merge the PR very soon, i need time to complete some refactoring.

**Comment by gr-jialeiwang** [comment]
thank you i will upgrade to v4.1 but i can't tell you the exact time 
when i finish the upgrade i will tell you immediately

**Comment by gr-jialeiwang** [comment]
i upgrade cto version4.1 and unfortunately
my log file only 14MB and until dashboard be shown there are 73MB memory be cost,
and if i access http://{my-project}/log-viewer/logs there's more memory be cost, maybe 100MB
even though the plugin is running fine if you only load today's log file.so anyway thank you for helping me

**Comment by bcat-eu** [comment]
@arcanedev-maroc I've got the same problem but we have a lot happening that generates info messages and a lot of log files

@gr-jialeiwang try following in your config

    'date'      => '{'.
            date('Y-m-d') . ','
            . date('Y-m-d', strtotime(date("Y-m-d") . "-1 days")) . ','
            . date('Y-m-d', strtotime(date("Y-m-d") . "-2 days"))
            . '}',

that would limit the log files to last 3 days including today (will work if your files use YYYY-MM-DD date format in names)

also you can activate swap, use `free -h` to check if your server has any, if not use following commands to setup a 8gb swap:

    sudo dd if=/dev/zero of=/var/swap.1 bs=1024 count=8M
    sudo mkswap /var/swap.1
    sudo swapon /var/swap.1

adjust `count=8M` to get another number of gb if you need it

that is what I had to do to make it work on our smaller staging server (using version 4.1)

**Comment by gr-jialeiwang** [comment]
@bcat-eu  
thank you for config and i used free -h to confirm the size of swap
i got swap 

> total       used       free     shared    buffers     cached
> Mem:          7.7G       7.1G       597M        27M       152M       6.1G
> -/+ buffers/cache:       896M       6.8G
> Swap:         8.0G         0B       8.0G

it seems not work and i dont know why 

i noticed that the page loading very slowly 
how can i improve it ? cache?

**Comment by bcat-eu** [comment]
@gr-jialeiwang well seems you have 8gb mamory and 8gb swap, no need to add any

as for your performance issue if you mean this log viewer, I'd limit the number of parsed configs

**Comment by gr-jialeiwang** [comment]
@bcat-eu 

this is my log-viewer.php

'pattern'       => [
        'prefix'    => Filesystem::PATTERN_PREFIX,    // 'laravel-'
        'date'      => Carbon::now()->toDateString(), // '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
        'extension' => Filesystem::PATTERN_EXTENSION, // '.log'
    ],

it seems load the log file very time if you click some link in page
so how about use static and keep the file into memory?

**Comment by bcat-eu** [comment]
@gr-jialeiwang it's your app on your server, I think you'll have to figure it out yourself :)

**Comment by gr-jialeiwang** [comment]
@bcat-eu 
actually its company's app and now the plugin is woking , slow but woking
so just keep in this way  ^_^

thank you for your hint and config its help me a lot
