### ISSUE TITLE
can i only read error data

### ISSUE THREAD

**Issue by gr-jialeiwang** [ARCANEDEV/LogViewer#92]
hi

my project's log file has a lot of debug data,
and i want to escape it to save page reading time .

can you tell me how to set config/log-viewer.php to only read error data please

Regards

**Comment by arcanedev-maroc** [comment]
Thanks for using this package.

There is no option to filter the logs with config/log-viewer.php

The only advise that i can give you for the time being is to set the minimum severity level for logs in your production: https://laravel.com/docs/5.3/errors#log-severity-levels

This way you can avoid the debug data to spam your logs files.

More details: #21

Best regards
