### ISSUE TITLE
is it a lack of memory?

### ISSUE THREAD

**Issue by gr-jialeiwang** [ARCANEDEV/LogViewer#93]
hi

i set config/log-viewer.php's pattern's date to Carbon::yesterday()->toDateString() then the plugin only load yesterday's log file for me and finally the dashboard is shown.
and the http://{my-project}/log-viewer/logs's fine too but,
when i access http://{my-project}/log-viewer/logs/2016-11-06/error the memory be eaten.

my yesterday's log file is only 15MB and since i accessed http://{my-project}/log-viewer/logs/2016-11-06/error until the page be shown there is 460MB memory be eaten.

and i change to another day that have 35MB log files and dashboard is shown too but,
when i access "http://{my-project}/log-viewer/logs/2016-11-04/error" then there is 500 error,
and i read the apache error-log and its allowed memory exhausted error again.

im not try [#91](https://github.com/ARCANEDEV/LogViewer/issues/91) yet, but 
maybe the plugin loads the log file many times in somewhere

can you check it please?

regards

**Comment by arcanedev-maroc** [comment]
I'm going to close this because it's a duplicated issue: #91 

Please, send your comments/progress/suggestions in your previous issue to consolidate the information.
