### ISSUE TITLE
Route [log-viewer::dashboard] not defined

### ISSUE THREAD

**Issue by Melcus** [ARCANEDEV/LogViewer#94]
I'm trying to include the viewer in our dashboard in an iframe  `  <iframe src="{{route('log-viewer::dashboard')}}" style="width:100%;height:1000px"></iframe>` and I get this `Route [log-viewer::dashboard] not defined` On local it works (windows) but not online (ubuntu). Any ideas?

**Comment by arcanedev-maroc** [comment]
Did you installed the package properly ?

Try to run `php artisan route:list` to check all your routes, including the `log-viewer` routes.

I'm also a windows user and i don't have this issue.

I think the best way to include the `log-viewer` dashboard is by using the [view composers](https://laravel.com/docs/5.3/views#view-composers).

Can you also give us your laravel & log-viewer versions and also your configuration to reproduce your issue?

**Comment by Melcus** [comment]
`log-viewer:publish --force` solved it. Forgot to update here. Thank you
