### ISSUE TITLE
Complete the translations

### ISSUE THREAD

**Issue by arcanedev-maroc** [ARCANEDEV/LogViewer#95]
Any help is appreciated to complete the translation of this new feature.

 * `logviewer::general.empty-logs`:

    * [x] `ar` (#87)
    * [x] `de` (#96)
    * [x] `en` (#87)
    * [x] `es` (#127)
    * [x] `et` (#108)
    * [x] `fa` (#138)
    * [x] `fr` (#87)
    * [x] `hu` (#310)
    * [x] `hy` (#100)
    * [x] `it` (#102)
    * [x] `ko` (#99)
    * [x] `nl` (#101)
    * [x] `pl` (#132)
    * [x] `pt-BR` (#140)
    * [x] `ro` (#204)
    * [x] `ru` (#100)
    * [x] `sv` (#98)
    * [x] `th` (#105)
    * [x] `tr` (#109)
    * [x] `zh` (#97)
    * [x] `zh-TW` (#116)

### New Translations:

  * [x] `id` (#143)
  * [x] `ja` (#145)
  * [x] `ms` (#309)
  * [x] `uk` (#275)

**Comment by Schnoop** [comment]
https://github.com/ARCANEDEV/LogViewer/pull/96

**Comment by vongola12324** [comment]
zh-TW #116
